- packages/http/package.json
- packages/http/src/forwarder/HttpForwarder.ts
- packages/http/src/forwarder/__tests__/HttpForwarder.spec.ts
- packages/http/src/forwarder/__tests__/__snapshots__/HttpForwarder.spec.ts.snap
- packages/http/src/forwarder/__tests__/__snapshots__/functional.spec.ts.snap
- packages/http/src/forwarder/__tests__/functional.spec.ts
- packages/http/src/forwarder/index.ts
- yarn.lock
Jira task: https://stoplightio.atlassian.net/browse/SL-71
> SL-71 HttpForwarder

- .circleci/config.yml
- README.md
Added a reported id to the circle ci.
It's a `chore` type of change, hence I did not create a story for it.
> Add test reported ID

- jest.base.js
- jest.config.js
- packages/cli/jest.config.js
- packages/core/jest.config.js
- packages/core/src/index.ts
- packages/http-server/jest.config.js
- packages/http/jest.config.js
- packages/http/src/mocker/generator/__tests__/JSONSchemaExampleGenerator.spec.ts
- fixes [SL-483](https://stoplightio.atlassian.net/browse/SL-483)
- generate at least one character for json schema generator test.
> Fix test code coverage

- packages/http/src/mocker/generator/JSONSchemaExampleGenerator.ts
- packages/http/src/mocker/generator/__tests__/JSONSchemaExampleGenerator.spec.ts
Issue: https://stoplightio.atlassian.net/browse/SL-2036
> Fix/sl 2036/schema faker fix

- packages/core/src/utils/__tests__/graphFacade.int.ts
- packages/core/src/utils/graphFacade.ts
Issue: https://stoplightio.atlassian.net/browse/SL-2028
> fix: SL-2028 fixed absolute paths handling

- packages/cli/src/commands/__tests__/__snapshots__/serve.func.ts.snap
- packages/cli/src/commands/__tests__/serve.func.ts
- packages/cli/src/commands/serve.ts
Issue: https://stoplightio.atlassian.net/browse/SL-2037
> feat: SL-2037 forbidding dirs to be supplied to --spec cli's arg

- packages/http-server/src/__tests__/server.spec.ts
- packages/http/package.json
- packages/http/src/mocker/generator/JSONSchemaExampleGenerator.ts
- yarn.lock
- setup jsf with sane defaults
> SL-2103 update jsf to stoplightio/json-schema-faker fork

- packages/core/src/loaders/http/httpLoader.ts
- packages/core/src/utils/configMergerFactory.ts
- packages/core/src/utils/graphFacade.ts
- packages/http/src/mocker/generator/JSONSchemaExampleGenerator.ts
- packages/http/src/router/__tests__/utils.ts
Thanks @P0lip for the suggestion!
> refactor: prefer import over requries

- README.md
> Removed mention of validation for now

- CONTRIBUTING.md
- README.md
Docs update
Longer readme, where the last sections are mostly only needed if contributing 
Nope 
Before: 
After:
> docs: updated contributing.md and readme.md

- CONTRIBUTING.md
- README.md
> docs: Docs fixes

- package.json
- yarn.lock
> fix: get rid of resolutions

- lerna.json
- package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
- yarn.lock
Fixed the `json-schema-faker` requirement problem
> Alpha .2 release

- README.md
> docs: fix up the FAQ section

- README.md
- packages/cli/package.json
- packages/cli/src/commands/__tests__/mock.spec.ts
- packages/cli/src/commands/mock.ts
- yarn.lock
> feat: CLI show endpoints and status SO-201

- lerna.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
> v3.0.0-alpha.3

- lerna.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
> v3.0.0-alpha.4

- lerna.json
- package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
- yarn.lock
Requesting a pull to stoplightio:master from stoplightio:feat/upd-graphite
Write a message for this pull request. The first block
of text is the title and the rest is the description.
> fix: upgrade graphite

- packages/cli/src/commands/__tests__/mock.spec.ts
- packages/cli/src/commands/mock.ts
- packages/cli/src/const/options.ts
- packages/cli/src/util/__tests__/createServer.unit.ts
- packages/http-server/src/__tests__/__snapshots__/getHttpConfigFromRequest.spec.ts.snap
- packages/http-server/src/__tests__/getHttpConfigFromRequest.spec.ts
- packages/http-server/src/__tests__/server.oas.spec.ts
- packages/http-server/src/server.ts
- packages/http/src/__tests__/fixtures/index.ts
- packages/http/src/__tests__/http-prism-instance.spec.ts
- packages/http/src/index.ts
- packages/http/src/mocker/HttpMocker.ts
- packages/http/src/mocker/__tests__/HttpMocker.spec.ts
- packages/http/src/mocker/__tests__/__snapshots__/HttpMocker.spec.ts.snap
- packages/http/src/mocker/__tests__/functional.spec.ts
- packages/http/src/mocker/negotiator/NegotiatorHelpers.ts
- packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts
- packages/http/src/mocker/negotiator/types.ts
- packages/http/src/types.ts
- packages/http/src/validator/__tests__/index.spec.ts
- packages/http/src/validator/utils/__tests__/config.spec.ts
- yarn.lock
1. Adds the `--dynamic` CLI flag
2. Prints something on the CLI if the dynamic is true
3. Changes the configuration object to be either "false" or a full configuration object (no more hidden defaults)
4. Adds tests
> --dynamic flag for CLI SO-217

- .circleci/config.yml
- lerna.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
- packages/http/src/mocker/negotiator/types.ts
- packages/tsconfig.base.json
- packages/tsconfig.json
- yarn.lock
and separate the download and execution commands
> chore: use the latest go image

- package.json
Warn: the first changelog is going to be huge
> feat: add changelog when releasing

- README.md
I do not know, but it feels better.
> readme: add arrows to external links

- README.md
> chore: set Accept validation as done

- CONTRIBUTING.md
- packages/cli/tsconfig.build.json
- packages/cli/tsconfig.json
- packages/core/tsconfig.build.json
- packages/core/tsconfig.json
- packages/http-server/tsconfig.build.json
- packages/http-server/tsconfig.json
- packages/http/src/mocker/__tests__/HttpMocker.spec.ts
- packages/http/src/validator/validators/params.ts
- packages/http/src/validator/validators/registry.ts
- packages/http/src/validator/validators/types.ts
- packages/http/tsconfig.build.json
- packages/http/tsconfig.json
- packages/tsconfig.base.json
- packages/tsconfig.build.json
- packages/tsconfig.json
@chris-miaskowski You might want to try this locally on your computer :)
> fix: small build tweaks

- packages/http-server/README.md
Be clear about the API we offer right now
Closes #349
> docs: be clear about the current API status

- README.md
- packages/http-server/src/__tests__/server.oas.spec.ts
- packages/http/src/__tests__/http-prism-instance.spec.ts
- packages/http/src/router/index.ts
- test-harness/gold-master-files/__path____pets_123?__server=https___petstore.io_v2___method___GET__.json
Improved the basePath FAQ and other README tweaks.
> Tweaking the README

- .circleci/config.yml
- packages/http-server/src/__tests__/__snapshots__/getHttpConfigFromRequest.spec.ts.snap
- packages/http-server/src/__tests__/getHttpConfigFromRequest.spec.ts
- packages/http-server/src/getHttpConfigFromRequest.ts
If you want such feature, use the Accept header instead
> feat: remove __contentType query parameter support

- packages/cli/tsconfig.build.json
- packages/core/tsconfig.build.json
- packages/http-server/tsconfig.build.json
- packages/http/tsconfig.build.json
We do not need test files in the final build output, so I removed them
> feat: do not compile test files

- .circleci/config.yml
_Bug fix_, _feature_, or _docs update_
_You can also link to an open issue here for all the info._
_What changes might users need to make in their application due to this PR?_
> chore: return for PRs

- README.md
We are only talking about the CLI-based HTTP mock server for now, so no need to mention other packages.
> docs: hide the packages for now

- packages/core/src/types.ts
- packages/http/src/validator/__tests__/index.spec.ts
- packages/http/src/validator/index.ts
I've checked the code multiple times and there is really no reason the validation process should be marked as async — it's indeed not.
This PR removes any doubts about it so it's going to be easier to reason about it
> Make the validation process sync

- .circleci/config.yml
Run harness test suite on macOS when we merge something in master and when we're releasing stuff. Closes #442 
SO-149
> test: run test suite on macos on master

- CHANGELOG.md
- lerna.json
- package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
- yarn.lock
> Release beta.6

- test-harness/specs/default_responses-AC-1.oas2.txt
- test-harness/specs/default_responses-AC-1.oas3.txt
- test-harness/specs/static_examples-AC-1.oas2.txt
- test-harness/specs/static_examples-AC-1.oas3.txt
- test-harness/specs/static_examples-AC-2.oas2.txt
- test-harness/specs/static_examples-AC-2.oas3.txt
Add tests for static examples - closes #414
> test: add e2e tests for static examples

- test-harness/index.ts
- test-harness/specs/parameters-ac1.oas2.txt
- test-harness/specs/parameters-ac1.oas3.txt
- test-harness/specs/parameters-ac2.oas2.txt
- test-harness/specs/parameters-ac2.oas3.txt
- test-harness/specs/parameters-ac3.oas2.txt
- test-harness/specs/parameters-ac3.oas3.txt
- test-harness/specs/parameters-ac4.oas2.txt
- test-harness/specs/parameters-ac4.oas3.txt
- test-harness/specs/parameters-ac5.oas2.txt
- test-harness/specs/parameters-ac5.oas3.txt
- test-harness/specs/parameters-ac6.only_oas3.txt
This PR adds tests to cover scenarios from #428 
Closes #428
> test: add query/headers/path parameters e2e tests

- test-harness/specs/manually-select-examples-AC-1.oas2.txt
- test-harness/specs/manually-select-examples-AC-1.oas3.txt
- test-harness/specs/manually-select-examples-AC-2.oas3.txt
- test-harness/specs/manually-select-examples-AC-4.oas3.txt
Add successful examples for #411, failing ones are in https://github.com/stoplightio/prism/pull/480
> test: add examples for manual example selection

- CHANGELOG.md
- packages/cli/package.json
- packages/http/src/types.ts
- test-harness/specs/static_examples-AC-3.oas3.txt
- yarn.lock
> respect oas3 nullables in schemas

- packages/cli/package.json
- yarn.lock
> Fix: correctly load encodings with no styles

- packages/http/README.md
While checking out #511 I noticed you noticed that the http client docs is effectively not up to date, that's totally my fault. This solves the problem.
> Update http client package docs

- CHANGELOG.md
- packages/cli/package.json
- test-harness/e2e-refs-handling.oas3.txt
- yarn.lock
> Upgrade http-spec

- CHANGELOG.md
- packages/cli/package.json
- test-harness/specs/allow-empty-value-2.oas2.txt
- test-harness/specs/allow-empty-value.oas2.txt
- yarn.lock
> fix: correctly handle allowEmptyValue

- .github/workflows/auto-approve.yml
- test-harness/README.md
_Bug fix_, _feature_, or _docs update_
_You can also link to an open issue here for all the info._
_What changes might users need to make in their application due to this PR?_
> docs: readme typos

- CHANGELOG.md
- packages/http-server/src/__tests__/server.oas.spec.ts
- packages/http-server/src/serializers.ts
- packages/http-server/src/server.ts
- test-harness/specs/E2E-Accept-Content-Negotiation-AC-1.oas2.txt
- test-harness/specs/E2E-Accept-Content-Negotiation-AC-1.oas3.txt
- test-harness/specs/E2E-Accept-Content-Negotiation-AC-15.oas2.txt
- test-harness/specs/E2E-Accept-Content-Negotiation-AC-15.oas3.txt
- test-harness/specs/E2E-Accept-Content-Negotiation-AC-4.oas2.txt
- test-harness/specs/E2E-Accept-Content-Negotiation-AC-4.oas3.txt
1. Changelog corrected
2. E2E tests corrected
3. Do not duplicate the serialiser definition
> Minor changes to Accept Header

- CHANGELOG.md
- docs/guides/errors.md
- packages/core/src/utils/__tests__/security.spec.ts
- packages/core/src/utils/security/handlers/utils.ts
- packages/http/src/mocker/HttpMocker.ts
- packages/http/src/mocker/errors.ts
- test-harness/specs/security-scheme-validation-AC-5.oas2.txt
- test-harness/specs/security-scheme-validation-AC-5.oas3.txt
- test-harness/specs/security-scheme-validation-AC-6.oas2.txt
- test-harness/specs/security-scheme-validation-AC-6.oas3.txt
> fix: Prism has not enough informations to return a 403 in any case

- CHANGELOG.md
- lerna.json
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
> Release 3.1.1

- README.md
Docs update for https://github.com/stoplightio/prism/issues/375
> docs: docker network

- package.json
- packages/core/src/factory.ts
- packages/http-server/src/server.ts
- packages/http/README.md
- packages/http/src/router/__tests__/index.spec.ts
- packages/http/src/router/__tests__/utils.ts
- packages/http/src/types.ts
- yarn.lock
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38156 has finally been merged and we can remove yet another terrible cast.
> refactor: remove casting thanks to new lodash types

- docs/getting-started/installation.md
- [N/A] Tests have been added (for bug fixes / features)
_docs update_
Was documented referencing the Spectral image, not Prism. Renamed example file for consistency. Adds flags for defined port and best practices. Let me know if there's anything different you'd like to see here.
No
> Updates example docker run commands

- .github/workflows/auto-approve.yml
- .github/workflows/markdown-links.yml
- CHANGELOG.md
- docs/guides/request-validation.md
Add markdown links checker so we do not give broken links to people and we know if any of these die along the way.
> Check all markdown links on PRs

- packages/http/src/mocker/generator/HttpParamGenerator.ts
- packages/http/src/mocker/generator/__tests__/HttpParamGenerator.spec.ts
> Pattern in example path generation

- CHANGELOG.md
- packages/http/package.json
- test-harness/specs/dynamic_json_additionalProperties_object.oas3.txt
- test-harness/specs/dynamic_json_responses_additionalProperties.oas3.txt
- yarn.lock
> Update JSON Schema Faker

- CHANGELOG.md
- packages/http/src/mocker/__tests__/HttpMocker.spec.ts
- packages/http/src/mocker/__tests__/__snapshots__/HttpMocker.spec.ts.snap
- packages/http/src/mocker/index.ts
- packages/http/src/validator/__tests__/functional.spec.ts
- packages/http/src/validator/validators/params.ts
- test-harness/specs/deprecated-keyword.only_oas3.txt
> fix: do not report an error with deprecated keyword

- docs/guides/multiple-documents.md
> docs: fix typo with the folder name

- .eslintrc.json
- .prettierrc.js
- package.json
- packages/cli/src/commands/mock.ts
- packages/cli/src/util/createServer.ts
- packages/cli/src/util/paths.ts
- packages/cli/src/util/runner.ts
- packages/core/src/__tests__/factory.test.ts
- packages/http-server/src/__tests__/getHttpConfigFromRequest.spec.ts
- packages/http-server/src/__tests__/server.oas.spec.ts
- packages/http/src/__tests__/client.spec.ts
- packages/http/src/__tests__/http-prism-instance.spec.ts
- packages/http/src/__tests__/utils.ts
- packages/http/src/forwarder/index.ts
- packages/http/src/mocker/index.ts
- packages/http/src/router/index.ts
- packages/http/src/router/matchBaseUrl.ts
- packages/http/src/router/matchPath.ts
- packages/http/src/validator/index.ts
- yarn.lock
> chore: reformat

- docs/guides/callbacks.md
- packages/http/src/mocker/callback/callbacks.ts
There's a lot of formatting because of eslint, but the relevant bits are here: https://github.com/stoplightio/prism/compare/feat/webhooks...feat/webhook-improvements?expand=1#diff-91872759342de667324152b94a1fc424L27
> Improve WebHooks calling chain

- CHANGELOG.md
- packages/cli/src/util/createServer.ts
> Add timestamp to CLI output

- CHANGELOG.md
- packages/http-server/src/server.ts
- test-harness/specs/cors/cors-headers-precedence.txt
- test-harness/specs/cors/cors-headers.txt
> Reflect request origin in CORS headers

- README.md
Added our Offset Earth profile same as https://github.com/stoplightio/spectral/pull/775
> Offset.Earth Badge

- README.md
- test-harness/helpers.ts
- test-harness/index.ts
_Refactor_
Test harness will fail after 3sec if prism instance has not been started correctly.
No
> Improved bootstrap of Prism instance in test harness

- packages/cli/src/const/options.ts
- packages/core/src/factory.ts
- packages/core/src/types.ts
- packages/http/src/forwarder/__tests__/index.spec.ts
- packages/http/src/forwarder/index.ts
_Feature_
Prism, when in proxy mode prints the exact upstream address which has been called during forwarding.
No
> Improved proxy logs

- packages/http/package.json
- packages/http/src/getHttpOperations.ts
- yarn.lock
> Using renamed json-ref-readers package

- packages/http/src/validator/validators/security/index.ts
It turns out there is a dedicated function in case you need to call map + mapLeft — bimap
> Prefer bimap

- CHANGELOG.md
- packages/cli/package.json
- packages/cli/src/const/options.ts
- packages/cli/src/util/__tests__/colorizer.spec.ts
- packages/cli/src/util/createServer.ts
- yarn.lock
> fix: put chalk as a dependency

- README.md
More consistent circle badge, and added download count.
> chore: we get a lot of downloads

- package.json
- yarn.lock
Adds all the dev dependencies explicitly so that our resolution file won't get us in trouble.
> Add explicit dev deps

- docs/getting-started/02-concepts.md
Pretty straight forward... :)
Cheers!
> Fixing typos

- CHANGELOG.md
- lerna.json
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
- packages/http/src/router/__tests__/index.spec.ts
- packages/http/src/router/index.ts
- test-harness/specs/routing/select-correct-method.oas3.txt
Closes #968 
Adding tests in a while…
> fix: disambiguate on methods when server validation is not enabled

- .gitignore
@karol-maciaszek you're going to like this 😄 
Ignore files generated by JetBrains IDEs: WebStorm/PhpStorm/Rider/IDEA/etc.
> chore: ignore files of Jetbrains IDEs

- packages/http/package.json
- test-harness/specs/validate-body-params/json-invalid-request-2.pc.txt
- yarn.lock
- upgraded http-spec
- fixed harness test due to http-spec@2.11.0 making params inferred from PC documents required
> http-spec upgrade

- .prettierrc.js
- CHANGELOG.md
- lerna.json
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http-server/src/__tests__/fixtures/petstore.no-auth.oas3.yaml
- packages/http-server/src/__tests__/server.oas.spec.ts
- packages/http-server/src/server.ts
- packages/http/package.json
- yarn.lock
> fix: do not override mock options

- packages/cli/package.json
Faster iterations when needing to try the CLI
> use transpile only in cli

- packages/http-server/README.md
Fixes https://github.com/stoplightio/prism/issues/1187
> Update README.md for http-server to have more thorough example code.

- README.md
Adds "Requirements" section to documentation, specifies `node` requirement.
> Add node requirements to documentation

- test-harness/specs/validate-path-params/path-param-with-hyphen.oas3.txt
- test-harness/specs/validate-query-params/query-param-with-hyphen.oas3.txt
> OpenAPI 3 harness tests for hyphen handling fix

- yarn.lock
> dedupe deps

- packages/cli/src/combinators.ts
- packages/cli/src/util/paths.ts
- packages/core/src/factory.ts
- packages/http/src/combinators.ts
- packages/http/src/mocker/callback/callbacks.ts
- packages/http/src/mocker/negotiator/NegotiatorHelpers.ts
- packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts
- packages/http/src/utils/runtimeExpression.ts
- packages/http/src/validator/index.ts
- packages/http/src/validator/validators/utils.ts
This PR moves all the combinators in a single file so we do not recreate them every time. Should help us keeping track of what we use.
> put all combinators in one file

- .circleci/config.yml
- CHANGELOG.md
- docs/getting-started/03-cli.md
- packages/cli/src/operations.ts
- packages/cli/src/util/runner.ts
- test-harness/README.md
- test-harness/specs/proxy/proxy-invalid-request-no.errors.txt
- test-harness/specs/proxy/proxy.invalid-request.txt
- test-harness/specs/proxy/proxy.passthrough-no-route.txt
- test-harness/specs/proxy/proxy.passthrough.txt
- test-harness/specs/proxy/proxy.valid-request.txt
- test-harness/specs/proxy/proxy.valid.txt
- test-harness/specs/proxy/proxy.validation.httpHeader.txt
- test-harness/specs/proxy/proxy.validation.httpResponse.txt
- yarn.lock
> no circular references

- CHANGELOG.md
- packages/http/src/forwarder/index.ts
> Do not ask for compressed responses

- CHANGELOG.md
- packages/cli/package.json
- test-harness/specs/validate-body-params/json-inference-invald-request.pc.txt
- test-harness/specs/validate-body-params/json-inference-invalid-request.pc.txt
- test-harness/specs/validate-body-params/json-inference-valid-request.pc.txt
- yarn.lock
Fixes: #1246 
~This PR is blocked by: https://github.com/stoplightio/http-spec/pull/110~
> Smart spec inference support for Postman

- README.md
Hi. I guess the link needs to update.
> doc: Fix doc link

- packages/http/src/mocker/negotiator/InternalHelpers.ts
- packages/http/src/mocker/negotiator/NegotiatorHelpers.ts
- packages/http/src/types.ts
Small refactor and changes that will make the code base better hopefully
> Remove conditions and use fp-ts

- packages/http/src/mocker/generator/HttpParamGenerator.ts
Unify conditions and use `else if` to stop evaluation early.
> chore:Use else if to return early

- package.json
- yarn.lock
Automated security vulnerability scanners are annoying but 🤷🏻‍♂️ easy fix! (Assuming it builds and tests pass)
> fix(deps): bump sanitize-html for security

- README.md
> fix(readme): npm downloads badge

- CHANGELOG.md
- lerna.json
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
> bumps 4.3.0

- README.md
Functionality for prism is often the same as functionality for hosted mocking, so let's try and get more folks over to the main roadmap.
> Help folks find the roadmap

- README.md
Mention OAS 3.1 on the README, we're proud of supporting it!
> docs: mention OAS3.1 support on README

- docs/guides/01-mocking.md
- docs/guides/03-validation-proxy.md
Just docs update for https://github.com/stoplightio/prism/issues/1563
> chore: update docs to reflect support for deprecated operations

- .circleci/config.yml
> fix: Fixed CI build

- package.json
- packages/http/src/client.ts
- yarn.lock
Bumping a few outdated dependencies, mostly our own minors/patches that seem low risk and AJV as it's got a few edge case fixes in there.
> Updated AJV and some other deps

- .circleci/config.yml
- .github/CODEOWNERS
- test-harness/index.ts
Addresses n/a
**Summary**
the test harness is timing out in circleci, this bumps some timings
**Checklist**
- The basics
- Tests
> increase timeouts needed for test harness

- .circleci/config.yml
as discussed this flag is needed to fix publishing releases
> add no verify access to lerna/yarn publish

- docs/guides/06-errors.md
Addresses docs for #1939
**Summary**
Doc update
**Checklist**
- The basics
- Tests
> Update errors to match #1939

- docs/getting-started/02-concepts.md
- docs/getting-started/03-cli.md
- docs/guides/01-mocking.md
- docs/guides/03-validation-proxy.md
Addresses #1982
**Summary**
Clarified behavior for omitting --errors and --validate-request
**Checklist**
- The basics
- Tests
> Pam 1982 request response validation

- docs/guides/03-validation-proxy.md
- yarn.lock
Addresses https://github.com/stoplightio/platform-internal/issues/11028
**Summary**
Upgrades minimist dependency to fix security issue flagged by dependabot.
**Checklist**
- The basics
- Tests
> update dependencies for dependabot alert

- packages/http-server/src/getHttpConfigFromRequest.ts
- packages/http/src/mocker/negotiator/InternalHelpers.ts
- packages/http/src/mocker/negotiator/NegotiatorHelpers.ts
- packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts
- test-harness/specs/range-status-codes/range-status-codes-AC-1.oas3.txt
- test-harness/specs/range-status-codes/range-status-codes-AC-2.oas3.txt
- test-harness/specs/range-status-codes/range-status-codes-AC-3.oas3.txt
- test-harness/specs/range-status-codes/range-status-codes-AC-4.oas3.txt
- test-harness/specs/range-status-codes/range-status-codes-AC-5.oas3.txt
- test-harness/specs/range-status-codes/range-status-codes-AC-6.oas3.txt
- test-harness/specs/range-status-codes/range-status-codes-AC-7.oas3.txt
- test-harness/specs/range-status-codes/range-status-codes-AC-8.oas3.txt
Addresses #2024
**Summary**
**Checklist**
- The basics
- Tests
> Feat: Support Ranges of Response Codes

- docs/getting-started/02-concepts.md
Added a content negotation section to the overview.
> content types statement

- test-harness/specs/references/E2E-Recursive-Array-Handling.oas3.1.txt
- test-harness/specs/references/E2E-Recursive-Array-Handling.oas3.txt
Adds tests for #2081 to cover the broken case for the OP. i was unable to reproduce locally.
> adds tests to validate #2081 recursive thru an array

- docs/guides/03-validation-proxy.md
Addresses #[2093]
Updated proxy URL example and added callout about the protocol requirement.
> Modified docs/guides/03-validation-proxy.md

- package.json
- yarn.lock
found that lerna had vulnerable dependencies. dependabot couldn't resolve this, so i am
> upgrade lerna to account for vulnerabilities

- packages/cli/package.json
- packages/http/package.json
- yarn.lock
addresses dependabot reported issue for uri-template-lite
> chore(deps): upgrade uri-template-lite

- toc.json
Fixed missing Faker file in toc
> Modified toc.json

- docs/getting-started/03-cli.md
> Added section for logging commands

- CHANGELOG.md
- lerna.json
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
**Summary**
**Checklist**
- The basics
- Tests
> release 4.12.0

- .circleci/config.yml
update `pipenv` command in response to release https://github.com/pypa/pipenv/blob/main/CHANGELOG.rst#2022813-2022-08-13
> replace pipenv lock -r with pipenv requirements

- CHANGELOG.md
- docs/guides/06-errors.md
- packages/http/package.json
- packages/http/src/mocker/errors.ts
- packages/http/src/mocker/generator/HttpParamGenerator.ts
- packages/http/src/mocker/generator/JSONSchema.ts
- packages/http/src/mocker/generator/__tests__/JSONSchema.spec.ts
- packages/http/src/mocker/index.ts
- test-harness/specs/generated-responses/too_complex-AC-1.oas3.txt
- yarn.lock
Addresses #2033
**Summary**
* upgrade json-schema-sampler to get better error type
* rejigger to allow prism specific error to be thrown
**Checklist**
- The basics
- Tests
> feat(http): detect complex schema error, improve error message

- docs/guides/06-errors.md
Addresses #2345
**Summary**
Added violation message and explanation for use of discriminators. 
**Checklist**
- The basics
- Tests
> Add discriminator error.

- docs/guides/06-errors.md
**Summary**
Missed an "ed". 
**Checklist**
- The basics
- Tests
> Modified docs/guides/06-errors.md

- .circleci/config.yml
**Summary**
**Checklist**
- The basics
- Tests
> update xcode executor to 13.4.1

- .circleci/config.yml
- package.json
- yarn.lock
Addresses #2319 
**Summary**
Updated node to latest 16.x version (required for lerna version bump)
Updated lerna to the latest version that includes the semver security patch
**Checklist**
- The basics
- Tests
> update lerna version, update node version

- README.md
- packages/cli/package.json
- yarn.lock
Addresses #2385 
**Summary**
Bumping the json-schema-ref-parser version brings in the changes required to better resolve all external file refs. 
**Checklist**
- The basics
- Tests
> bump json-schema-ref-parser version

- docs/guides/07-http-client.md
Addresses #2414
**Summary**
Update docs to reflect the correct config values needed for proxy mode.
> chore: update prism client docs with correct config values

- .github/workflows/jira-issue-label-added.yaml
**Summary**
**Checklist**
- The basics
- Tests
> New jira label workflow: Create jira-issue-label-added.yaml

- CHANGELOG.md
- lerna.json
- packages/cli/package.json
- packages/core/package.json
- packages/http-server/package.json
- packages/http/package.json
> chore: changelog for 5.5.4

- package.json
Addresses https://github.com/stoplightio/prism/security/dependabot/84
> attempt to fix Dependabot alert #84

- .github/workflows/pr-title.yml
STOP-267
**Summary**
require conventional commit format PR titles
> STOP-267 require conventional commit format PR titles

- release-please-config.json
> fix(ci): STOP-267 improve auto-release config

- .release-please-manifest.json
- release-please-config.json
> fix(ci): release please simpler config

- .github/workflows/release.yml
> fix(ci): release please with checkout

- .github/workflows/release.yml
> fix(ci): remove root from release please

- .github/workflows/jira-issue-label-added.yaml
**Summary**
**Checklist**
- The basics
- Tests
> chore: STOP-348 update jira issue workflow

- .github/workflows/jira-issue-label-added.yaml
**Summary**
**Checklist**
- The basics
- Tests
> chore: add maintenance team

- .github/workflows/jira-issue-label-added.yaml
**Summary**
**Checklist**
- The basics
- Tests
> Chore: Update prism jira action workflow with new team name (prism edition)

- package.json
- yarn.lock
> chore(deps): upgrade lerna

- packages/cli/package.json
- packages/http-server/package.json
- packages/http/package.json
- packages/http/src/mocker/index.ts
- yarn.lock
Addresses #STOP-184
**Summary**
For big and complex OpenAPI spec performance improved also for circular reference mapping done and Added the latest @stoplight/JSON version
**Checklist**
- The basics
- Tests
> fix: version update and bundled_issue changes

- .release-please-manifest.json
- release-please-config.json
Addresses #[stop-537]
**Summary**
Continuation of https://github.com/stoplightio/prism/pull/2583/files.
**Checklist**
- The basics
- Tests
> chore(ci): back to release please without root p2

- package.json
- yarn.lock
Addresses 
[STOP-2171](https://smartbear.atlassian.net/browse/STOP-2171)
**Summary**
bump up jsonpath-plus to 10.2.0v
**Checklist**
- The basics
- Tests
[STOP-2171]: https://smartbear.atlassian.net/browse/STOP-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(deps): bump up jsonpath-plus to 10.2.0v
