stoplightio/prism

packages/http-server/src/__tests__/server.spec.ts, packages/http-server/src/server.ts
async `createServer` feels unnecessary. `.listen()` is already async, and we don't need to load before listening.
=> no need for createServer to be async

packages/http-server/src/__tests__/server.spec.ts, packages/http-server/src/server.ts
Issue: https://stoplightio.atlassian.net/browse/SL-216
For fastify and it's request object we need to strip the query part from url. It looks better for express - there we have all necessary parameters prepared and in-place.
From the other side, we can't easily migrate to string-url solution (because of oas3 servers shape / variables / base path).
Maybe a good solution would be to support both. Url as a string and as an object. If user gets into trouble because of witchcraft he did in server list + base url + variables he can switch to `url: { path: string, basePath: string, query: {} }`. For most of the cases `url: string` will do the job.
What do you think?
@marbemac @pytlesk4 @chris-miaskowski
=> SL-216 Stripping query part from url

README.md, package.json, packages/cli/package.json, packages/cli/src/__tests__/serve.spec.ts, packages/core/README.md, packages/core/src/__tests__/factory.spec.ts, packages/core/src/factory.ts, packages/core/src/types.ts, packages/http-server/src/__tests__/server.spec.ts, packages/http/src/__tests__/http-prism-instance.spec.ts, packages/http/src/forwarder/HttpForwarder.ts, packages/http/src/forwarder/__tests__/HttpForwarder.spec.ts, packages/http/src/forwarder/__tests__/__snapshots__/HttpForwarder.spec.ts.snap, packages/http/src/forwarder/__tests__/functional.spec.ts, packages/http/src/forwarder/__tests__/index.spec.ts, packages/http/src/router/__tests__/index.spec.ts, packages/http/src/router/index.ts, packages/http/tsconfig.build.json, packages/tsconfig.base.json, packages/tsconfig.build.json
This PR will:
1. Change the Readme a little bit so that's more informative. There's still a *LOT* of work to do, but that's a start.
2. Transform `components.router.route` to a sync function, because there's nothing async in it (I hope it's the only occurrence but there might be other)
3. Remove the need of the `IHttpOperation` instance coming from graphite. In case it is absent, it'll read the data from the request object directly. Please note that, in my opinion, the IHttpOperation should be completely removed, because the only reason it's there it's because it needs to read the server/base Url — which can be done externally. If you agree with such change, I can make that happen.
4. Add/fix/rewrite tests
5. Fix TSLint that was not running properly on the packages
=> SL-1619 - Prism forwarder can work without an API in place

packages/cli/tsconfig.build.json, packages/cli/tsconfig.json
- Class constructor Command cannot be invoked without 'new'
SL-2021
=> fix: running `prism` cli threw exception [SL-2021]

packages/core/package.json, packages/core/src/utils/graphFacade.ts, packages/http/src/__tests__/fixtures/petstore.oas2.yaml, packages/http/src/__tests__/http-prism-instance.spec.ts, yarn.lock
Issue: https://stoplightio.atlassian.net/browse/SL-2029
- upgraded graphite to 3.x
- enabled yaml support
=> Chore/sl 2029/graphite upgrade

packages/http-server/src/__tests__/server.spec.ts, packages/http-server/src/server.ts
Issue: https://stoplightio.atlassian.net/browse/SL-2030
Disabled default fastify's body serialization. Prism has already taken care of it.
=> fix: SL-2030 disabled fastify's body serializing

packages/core/src/utils/graphFacade.ts, yarn.lock
After a very long investigation I found out the reason Prism was crashing is because it was internally using an old `@stoplight/json` which didn't contain the `diagnostic` field that was required in graphite, making it crash. Removing the lock file and regenerate it made it work again correctly.
It's so sad.
=> Update yarn lock file so that prism works

install.sh
This PR modifies the grep expression used to understand the latest tag to make sure only the `v2` ones get selected — so we can release pre-release tags for v3 without having the risk of making messes with people willing to install Prism.
=> feat: change install script to select v2 only tags SS-31

packages/http/src/__tests__/http-prism-instance.spec.ts, packages/http/src/router/__tests__/index.spec.ts, packages/http/src/router/__tests__/utils.ts, packages/http/src/router/errors.ts, packages/http/src/router/index.ts, packages/http/src/router/types.ts
This PR will make sure to throw a special exception in case the current path has been matched, but it wasn't possible to find an appropriate method.
We'll catch these exceptions and return the appropriate status codes in a follow up PR.
Highlights:
1. Dry some functions that were unexpectedly complicated and/or accumulating state over time (`matchServer`, `randomPath`)
2. Do not creare `Error` objects in place where they're not thrown, otherwise the stack trace is wrong and you have no idea where the exception happened. (This made me lose some time)
3. Refactored the `route` method to not accumulate the state over time with global `booleans`, but rather create a `matches` object and find the correct thing to do using a series of filters
4. Added tests for the new scenario.
SO-184
=> 405 —  Method not allowed — SO-184

packages/core/src/utils/graphFacade.ts, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http-server/src/server.ts, packages/http/src/mocker/errors.ts, packages/http/src/router/errors.ts, packages/http/src/types.ts
It turns out Fastify is a little bit too opinionated with regards to the error format; so if you use `reply.send` with an `Error` object it will copy only some particular fields and completely ignore the others, which we need for `application/problem+json`.
I've tried every possible solution, but it's scenario they just do not support. I know this is not ideal, but hopefully I'll be able to get rid of this asap
I've also modified the tests to make sure the error payload is always an `application/problem+json`
=> fix: error serialisation SO-195

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
The instructions here were out of date, `yarn setup` does not exit.
Also took this opportunity to improve the PR template to match Spectral a bit more.
=> Fixed CONTRIBUTING.md

packages/cli/package.json, packages/core/src/loaders/http/httpLoader.ts, packages/core/src/utils/__tests__/graphFacade.int.ts, packages/core/src/utils/graphFacade.ts, yarn.lock
This PR fixes the "spec download from internet experience".
Unfortunately I had to change a little bit the mechanism because apparently Graphite has some problems with initialising stuff from memory directly and I've been trying to debug it for the whole day, without no luck.
I want to get this out, so I decided to introduce a little bit of technical debt which can easily be repaired in order to get this out. Given this is confined in the CLI only (In a non future breaking way) and not in Prism itself, it should not be a big deal.
=> fix: make sure http download works

README.md, packages/http/src/__tests__/fixtures/index.ts, packages/http/src/mocker/__tests__/__snapshots__/functional.spec.ts.snap, packages/http/src/mocker/__tests__/functional.spec.ts, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts, packages/http/src/types.ts
This PR will make sure Prims will look for `422` responses in the document for invalid requests first; if not defined, Prism will generate one and not use the `default` response, if defined.
This replace the following behaviour: look for `400` response and if not defined, use the `default` response and, if not defined, then throw a `422`
=> fix: look for 422 for invalid requests

.circleci/config.yml, package.json
1. Creates a GitHub Release when publishing the package on Npm
2. Uploads the 3 binaries in the newly created release when workflow is manually approved
3. New scheme, `3.x.x-alpha`
=> GitHub Releases and binary uploads

README.md, packages/cli/src/commands/mock.ts, packages/core/src/utils/graphFacade.ts
1. Correctly reveals yml files as yaml for graphite
2. Handles startup exceptions and prints them out
3. Updates the README
=> Prism should read yml files too SO-200

lerna.json, packages/cli/README.md, packages/cli/package.json, packages/core/package.json, packages/core/src/loaders/http/httpLoader.ts, packages/core/src/utils/__tests__/graphFacade.int.ts, packages/core/src/utils/graphFacade.ts, packages/http-server/package.json, packages/http/package.json, yarn.lock
Gets rid of `node-tmp` entirely and uses Graphite to init the stuff from memory
=> refactor: get rid of node-tmp

packages/http/src/forwarder/HttpForwarder.ts, packages/http/src/forwarder/__tests__/HttpForwarder.spec.ts, packages/http/src/forwarder/index.ts
feat(http-forwarder): add support for timeout and cancelToken
A slight improvement to HTTP Forwarder. Having timeout and cancel token is quite useful for components such as request-maker.
Timeout is not configurable per given request and the request cannot be really cancel
See above.
Nope.
(e.g. detailed explanation, related issues, links for us to have context, eg. Stack Overflow, issues outside of the repo, forum, etc.)
=> feat(http-forwarder): add support for timeout and cancelToken

.circleci/config.yml, packages/cli/.gitignore, yarn.lock
I do not know if this happens because of #312 —  but the master build to get the artefacts up is broken. This will fix it!
=> fix: try to publish first, and then publish binaries

.circleci/config.yml, packages/cli/src/commands/__tests__/mock.spec.ts, packages/cli/src/commands/mock.ts, packages/core/src/factory.ts, packages/core/src/types.ts, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http/package.json, packages/http/src/index.ts, packages/http/src/mocker/HttpMocker.ts, packages/http/src/mocker/__tests__/HttpMocker.spec.ts, packages/http/src/mocker/__tests__/functional.spec.ts, packages/http/src/mocker/generator/JSONSchema.ts, packages/http/src/mocker/generator/__tests__/JSONSchema.spec.ts, packages/http/src/types.ts, packages/tsconfig.json, yarn.lock
This PR implements the strategy we agreed for static examples generation.
1. Removes the forced `true` flag
2. Uses OpenAPI Sampler in case the static example generation is enabled
3. I _had_ to move the `generate` argument for `HttpMocker` because of the weird configuration merger thing which I do not want to touch right now
4. Adds a bunch of tests
---
As you can see from the code, I had to add an additional function that takes a regular JSON Schema and transforms it to something that OpenAPI Sampler can effectively use to generate static examples.
Maybe we could do it the other way around, but this is a followup though.
SO-225
---
If this gets merged:
https://github.com/Redocly/openapi-sampler/pull/10
I can remove the horrible function I had to wrote myself to walk through the schema …
=> Static Examples generation

packages/cli/tsconfig.build.json, packages/cli/tsconfig.json, packages/core/tsconfig.build.json, packages/core/tsconfig.json, packages/http-server/tsconfig.build.json, packages/http-server/tsconfig.json, packages/http/src/validator/__tests__/index.spec.ts, packages/http/tsconfig.build.json, packages/http/tsconfig.json, packages/tsconfig.json, packages/tsconfig.test.json
TypeScript's server sometimes goes just nuts and shows errors only after minutes and minutes of usages.
I looked at its source code *yet another time* and I hope this PR will settle the errors from VSCode. Basically VSCode thinks it needs to compile the code but it's not true, so I've transferred as much options as possible to the build files.
=> fix: transfer rootDir and out to build configuration files

packages/http/package.json, packages/http/src/mocker/__tests__/HttpMocker.spec.ts, packages/http/src/mocker/generator/JSONSchema.ts, yarn.lock
Thanks to the new version I can now remove the fallback I had to implement in order to make it generate the examples.
Curiously, the new version is correctly giving the precedence to `default` values over the examples, which is indeed correct.
=> feat: update openapi-sampler

jest.config.js, packages/http-server/package.json, packages/http-server/src/server.ts, yarn.lock
Adds the parser for form body data so that Fastify will not block the request.
This can be only tested from the harness, because the Fastify testing utilities bypass the whole parsing/content type; harness though is being rebuilt in #372 ; so I think we need to coordinate here.
Closes #380
=> HTTP Server should parse formbody data

README.md, azure-pipelines.yml
1. Add badges, now the status in master is more important since we're doing additional stuff than regular PRs
2. Azure stuff runs on tags and master branch
=> chore: azure on master and tags

packages/core/src/factory.ts, packages/core/src/types.ts, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http/src/__tests__/http-prism-instance.spec.ts, packages/http/src/forwarder/HttpForwarder.ts, packages/http/src/router/__tests__/index.spec.ts, packages/http/src/router/index.ts
The following PR extends the usage of fp-ts to the routing package as well by basically making sure it does not throw exceptions anymore, but rather use the `Either` object to express an error object.
With this — the router and the mocker finally compose because the type match (they both return an `Either<Error, T>`.
Extend the `Either` usage to the router was indeed the easy part: https://github.com/stoplightio/prism/pull/402/files#diff-f9a10b37616fb5669ecd5218fc8535c9L16
The problem started when I started to integrate and try to compose the new function in the mega-file-to-split:
1. The whole flow is sync apart from the edge case when we need to employ the forwarder, and this requires an additional abstraction layer
https://github.com/stoplightio/prism/pull/402/files#diff-47c5dc2d65fd624 …
=> Expand fs-ts in Prism's router 

.circleci/config.yml
I spent 10 minutes to download it in a cross platform way and today I realised it's not used anymore.
I'm sorry, I'm 30 now.
=> chore: remove unused dockerize

packages/http/src/mocker/negotiator/NegotiatorHelpers.ts
While recording the video for Prism I noticed that the negotiator does not really tell you when a response is being created *because* of the default response. I added a new log line so that's less confusing
=> Tell the user we're using the default response

CHANGELOG.md, docs/guides/cors.md, packages/cli/src/commands/__tests__/mock.spec.ts, packages/cli/src/commands/mock.ts, packages/cli/src/util/createServer.ts, packages/core/package.json, packages/http-server/package.json, packages/http-server/src/server.ts, packages/http/package.json, packages/http/src/__tests__/http-prism-instance.spec.ts, packages/http/src/index.ts, packages/http/src/mocker/HttpMocker.ts, packages/http/src/mocker/__tests__/HttpMocker.spec.ts, packages/http/src/mocker/__tests__/functional.spec.ts, packages/http/src/types.ts, packages/http/src/validator/__tests__/functional.spec.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/utils/__tests__/config.spec.ts, test-harness/specs/cors/cors-headers-disabled.txt, test-harness/specs/cors/cors-headers-precedence.txt, test-harness/specs/cors/cors-headers.txt, yarn.lock
This PR installs the CORS middleware to the Prism instance when the `--cors` flag is enabled (which is enabled by default).
Docs and changeling added as well
Closes #412
=> CORS support

README.md
Tests will fail because there's no pipeline at all for v2 binaries.
=> Correctly write the docker command for V2

CHANGELOG.md, packages/cli/package.json, packages/http/src/validator/deserializers/index.ts, packages/http/src/validator/deserializers/style/__tests__/__snapshots__/delimited.spec.ts.snap, packages/http/src/validator/deserializers/style/delimited.ts, packages/http/src/validator/validators/body.ts, test-harness/specs/parameters-ac7.oas2.txt, test-harness/specs/parameters-ac8.oas2.txt, yarn.lock
Closes #498
This PR updates the http spec with the version that supports the CommaDelimited enum value, adds a serialiser for it and uses it for the payload in case it's necessary.
Note — I know this is not exactly a great piece of code, but unfortunately there's no other way to make this right unless we dismantle the whole validation system, which won't happen in this PR.
=> fix: accept and handle csv collection format

packages/cli/src/util/createServer.ts, packages/core/src/factory.ts, packages/core/src/types.ts, packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http-server/src/server.ts, packages/http-server/src/types.ts, packages/http/README.md, packages/http/src/__tests__/http-prism-instance.spec.ts, packages/http/src/mocker/HttpMocker.ts, packages/http/src/mocker/__tests__/HttpMocker.spec.ts, packages/http/src/mocker/__tests__/functional.spec.ts, packages/http/src/types.ts, packages/http/src/validator/__tests__/functional.spec.ts, packages/http/src/validator/__tests__/index.spec.ts
This PR back ports some of the changes I'm doing to the HttpClient to Prism master branch
1. Rename the `configObj` variable name so that we can use object auto-assigning (or whatever that feature is)
2. All configuration now must at least be an `IPrismConfig` — we were casting to it anyway so it's probably better be explicit and stop pretending to be super generic
3. Use `map + getOrElse` instead of `fold` — is semantically more correct.
4. More the `cors` option away from the `IHttpConfig` object
=> Backport client stuff in Prism

packages/core/src/factory.ts, packages/core/src/types.ts, packages/http-server/src/server.ts, packages/http-server/src/types.ts, packages/http/README.md, packages/http/src/index.ts, packages/http/src/mocker/negotiator/InternalHelpers.ts, packages/http/src/types.ts
This PR is another back port from the work I've been doing on the HTTP Client that I thought it would be a good idea  to bring in master as soon as possible.
This is still to make sure the final PR it's not a 🐲 dragon 🐲 to review.
* Rename `TSomething` to `Something` — the Hungarian era is over
* Stop pretending that components can just be undefined and skip entire parts of the code. Currently if the `router` component is not provided, Prism will just *not* do anything. I've modified this behavior to make the `router` component mandatory. Either you give me what I need to do my job or get out of here
* Make sure that, by definition, either the mocker or the forwarder is passed as a component
For an easier review, disable whitespaces from the diff:
➡️ …
=> refactor: make Prism's Input and Output mandatory

package.json, packages/core/src/__tests__/factory.test.ts, packages/core/src/factory.ts, packages/core/src/types.ts, packages/http/src/validator/__tests__/__snapshots__/functional.spec.ts.snap, packages/http/src/validator/__tests__/functional.spec.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/index.ts
This PR is yet another back port from the HTTP Client changes were doing. We're still trying to make sure the final PR is not a 🐲 dragon 🐲 
* Move the logic to understand whether the validator should be ran or not on the caller, and not the validator itself. This allows to remove the need of passing the whole configuration object
* The output parameter for the `validateOutput` function is now mandatory. If you do not have it, you've got nothing to validate.
* I've moved the enablement tests from the validator function to the factory function, which is where the real logic is happening.
=> Move the validator enablement out of the validator

CONTRIBUTING.md, test-harness/index.ts
Instead of swallowing the error, let's cleanup using the `finally` clause
=> test harness: do not swallow exceptions

packages/http/src/mocker/negotiator/InternalHelpers.ts, packages/http/src/types.ts
It turns out fp-ts has already a `NonEmptyArray` definition which is definitely better than mine.
=> refactor: use fp-ts non empty array

CHANGELOG.md, packages/cli/src/util/createServer.ts
Closes #644 
Bug fix
Cli is trying to kill subprocess even if it is not running in multi-process mode. It results in no nice-looking line `✖ fatal Cannot read property 'kill' of undefined`.
This fix moves logging of errors to the place where the context (single/multiprocess) is known. `.kill` will be invoked only in the latter context.
No
=> fix: killing subprocess only if prism is running in multiprocess mode

CHANGELOG.md, README.md, docs/guides/client.md, package.json, packages/http-server/src/server.ts, packages/http/README.md, packages/http/src/validator/__tests__/__snapshots__/functional.spec.ts.snap, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/index.ts
This PR is implementing two checks missing in the output validation that are required according to #429 
1. If the media type of the response does not match the media type in the document, we add an error
2. If the returned status code is *not* the one defined in the document and it's between 200 and 299, then it's an error, otherwise a warning.
I've added tests and reorganised these since I think we were a bit too aggressive with the mocking (and not cleaning them up)
Closes #429
=> feat: contract testing: add missing output checks

.circleci/config.yml
Closes #585
This PR introduces automatic docs deployment.
1. I added a private repo of mine to Studio.
2. That repo was also connected to CircleCI.
3. Took the token and url from `Publish` tab in Studio and created env variables in CircleCI.
When a change to `/docs` files or `README.md` was pushed to the repository with a new tag, the docs were published and visible to the world.
This `config.yml` was used for the mentioned repo.
```yml
version: 2.1
orbs:
stoplight: stoplight/cli@0.0.2
jobs:
build:
docker:
- image: circleci/node:10
steps:
- checkout
- run:
name: Greeting
command: echo Hello, world.
- run:
name: Print the Current Time
command: date
workflows:
version: 2
build:
jobs:
- build:
filters:
branches:
ignore: /.*/
tags:
only: /^v.*/
- stoplight/analyze:
filters:
branches:
ignore: …
```
=> automatic docs deploy

.circleci/config.yml, CHANGELOG.md, package.json, packages/http/tsconfig.build.json, yarn.lock
This is kind of a nasty TS to JS bug I found while trying to use Prism for its hosted version
Fundamentally given that it is a monorepo when generating the types for the current project the references points to the source code:
It goes without saying that such path does not exist in the published package, since that is instead found in `@stoplight/prism-core` package.
If you're using JavaScript, you won't even notice this bug. However, if you're using TypeScript and the `http` package, you'll notice some functions will return `any` instead of the correct interface (because TypeScript can't find the types, it will assume `any`).
This PR will use `ttypescript` project (a declarative wrapper for the TS compiler API) and adding a dropbox developed plugin that will rewrite the generated files …
=> fix: type import rewrite

packages/http-server/README.md, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http-server/src/server.ts, packages/http-server/src/types.ts, packages/http/src/index.ts
It turns out that although we're claiming that the `components` object is not required, it is indeed required because the logger instance is always required. 
This PR fixes this so that when using the http raw client package to have the hosted Prism version I do not incur in the problem of having something required not passed because of TypeScript not complaining.
=> fix: logger component is always required

.circleci/config.yml
Our docker images are based on node 12 and Windows tests run on node 12. We're on node 12, let's claim that.
=> Use node 12

.circleci/config.yml
Freeze `yarn.lock` to not be overwritten by the CI.
=> fix: do not rewrite yarn.lock on install

packages/http/tsconfig.build.json
It turns out the Regex I was using was too loose and missing different rewrites that we need. This PR will enlarge the captured stuff so no matter how far you are from `core/src`, it will be correctly rewritten into `@stoplight/prism-core`
=> fix: more comprensive import rewrite

.circleci/config.yml, package.json
#701 introduced a change to fix imports like `"../../core/src"` showing up in `.d.ts` files. However, if you install the latest version (v3.1.1) of `stoplight/prism-cli`, you'll see that the relative imports still exist in the built package, as no version has been published after this change.
Additionally, the `build` step in `package.json` still reads: `tsc --build ./packages/tsconfig.build.json`; this PR updates it to use `ttsc` instead, so that type files are created correctly when building locally. The CircleCI config has also been updated to use this build script instead of the one-off `npx` command.
=> fix(build): Use ttsc for compiling

packages/http/src/validator/__tests__/__snapshots__/functional.spec.ts.snap, packages/http/src/validator/__tests__/functional.spec.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/index.ts
Closes #774
* Calls the media type return validator only if the selected response has contents with a media type
* Uses now `typeIs.is` function library so that we can match stuff with charset headers as well instead of a simple equality check
=> fix: trigger media type validation only when defined in the response

docs/getting-started/installation.md, packages/cli/src/util/createServer.ts, packages/core/src/logger.ts
This PR moves away some CLI specific things from the core package and puts them in the CLI.
=> Refactor: move CLI specific logging options

docs/guides/mock-responses.md
- Grammar fixes "nor ... or" -> "neither ... nor", "an response" -> "a response"
- Tidy up sentence structure to hopefully be more readable
- "string" and "number" were the wrong way around
=> Docs: minor fixes in mock response guide

Dockerfile
This PR will add a small check so that when the build arg is `development` the built docker image will link the local source instead of installing the remote npm package.
I've already modified DockerHub so that it's set to a different value and using the npm packages.
On a different note, I think it's time to rethink the docker image we're building since it's not in the way it should be. I have a 8h flight on my way, I'll probably hack something while in there.
=> fix local docker build image

CHANGELOG.md, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts, test-harness/specs/content-negotiation/E2E-Accept-Content-Negotiation.empty.oas3.txt
This PR modifies the negotiation in the way it looks for content in case the `Accept` header is invalid or not provided.
1. It will look for an _explicit_ `*/*` content type in the current response
2. If not found, it will look for an `application/json` one
3. If not found, it will take the first one on the list.
Closes #500
For some reason Prettier decided to reformat the whole file so please review from here: https://github.com/stoplightio/prism/pull/802/files?utf8=✓&diff=unified&w=1
=> fix: treat emtpy Accept header as */*

packages/http-server/src/server.ts
```diff
- Violation: response,body,id should match format "int64"
+ Violation: response.body.id should match format "int64"
```
=> fix: use points to separate paths

CHANGELOG.md, packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http/src/mocker/callback/__tests__/callbacks.spec.ts, packages/http/src/validator/validators/__tests__/__snapshots__/utils.spec.ts.snap, packages/http/src/validator/validators/__tests__/utils.spec.ts, packages/http/src/validator/validators/utils.ts, test-harness/specs/validate-body-params/form-data-invalid-request.oas2.txt, test-harness/specs/validate-body-params/form-data-invalid-request.oas3.txt, test-harness/specs/validate-body-params/json-invalid-request-2.oas2.txt, test-harness/specs/validate-body-params/json-invalid-request-2.oas3.txt, test-harness/specs/violations/value-not-in-enum.httpResponse.txt
PR to handle the `allowedValues` in the `params` object (if present) to print better messages.
=> feat: handle allowedParams

packages/cli/src/util/createServer.ts, packages/core/src/__tests__/factory.test.ts, packages/core/src/factory.ts, packages/core/src/types.ts, packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http/src/__tests__/__snapshots__/http-prism-instance.spec.ts.snap, packages/http/src/__tests__/client.spec.ts, packages/http/src/__tests__/http-prism-instance.spec.ts, packages/http/src/mocker/generator/__tests__/HttpParamGenerator.spec.ts, packages/http/src/validator/validators/security/handlers/index.ts, test-harness/specs/proxy/proxy.passthrough-no-route.txt
#805 point 3
[Review with no whitespaces](https://github.com/stoplightio/prism/pull/808/files?utf8=✓&diff=unified&w=1)
This PR will short circuit the error handler in case the `errors` flag is set to false and the proxy is on — so we can still proxy the request although all the validation checks will not be performed since we have no idea what resource the user is trying to hit.
=> Keep proxying if resource is not found

packages/http/src/validator/validators/security/index.ts
The following PR brings some significant simplification to the security checks that were made in Prism.
It literally took me ages to understand what was going on and why some choices were made so far — I guess this part definitely went out of control.
Hopefully this PR, although not 100% complete (but honestly I'm so tired of working on this section) will bring some clarity and order so that in the next flight refactor it one more time will be easier.
=> refactor: make security validations easier to reason about

packages/http/src/validator/validators/__tests__/__snapshots__/utils.spec.ts.snap, packages/http/src/validator/validators/__tests__/headers.spec.ts, packages/http/src/validator/validators/__tests__/path.spec.ts, packages/http/src/validator/validators/__tests__/query.spec.ts, packages/http/src/validator/validators/__tests__/utils.spec.ts, packages/http/src/validator/validators/body.ts, packages/http/src/validator/validators/params.ts, packages/http/src/validator/validators/utils.ts
Get rid of the throw statement and handle it correctly with the helper provided by the Option monad.
=> refactor: handle validation exception correctly

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/core/package.json, packages/http-server/package.json, packages/http/package.json, packages/http/src/mocker/__tests__/HttpMocker.spec.ts, packages/http/src/mocker/index.ts, packages/http/src/validator/validators/body.ts
=> Parsing URL-Encoded body for runtime expressions

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/core/package.json, packages/http-server/package.json, packages/http-server/src/server.ts, packages/http/package.json, test-harness/specs/violations/input-only-no-500.txt
It turns out that we were returning a 500 even if there were just Input violations in the current request — but in that case the negotiation process is already giving us the response we want to return; the 500 transformation is only required for *output* violations.
Please approve but do not merge, so I can bundle this in a patch release.
=> fix: 500 only for output validation errors

packages/cli/src/util/createServer.ts, packages/cli/src/util/paths.ts, packages/core/src/__tests__/factory.test.ts, packages/core/src/__tests__/utils.ts, packages/core/src/factory.ts, packages/http-server/src/server.ts, packages/http/README.md, packages/http/src/forwarder/index.ts, packages/http/src/mocker/__tests__/HttpMocker.spec.ts, packages/http/src/mocker/callback/callbacks.ts, packages/http/src/mocker/generator/HttpParamGenerator.ts, packages/http/src/mocker/index.ts, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts, packages/http/src/utils/parseResponse.ts, packages/http/src/utils/runtimeExpression.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/index.ts, packages/http/src/validator/validators/__tests__/headers.spec.ts, packages/http/src/validator/validators/__tests__/path.spec.ts, packages/http/src/validator/validators/__tests__/query.spec.ts, packages/http/src/validator/validators/body.ts, packages/http/src/validator/validators/params.ts, packages/http/src/validator/validators/security/index.ts, packages/http/src/validator/validators/utils.ts
Let's use the same conventions that all the other projects using fp-ts are using.
=> refactor: rename fp-ts imports

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/core/package.json, packages/http-server/package.json, packages/http/package.json, packages/http/src/validator/validators/__tests__/utils.spec.ts, packages/http/src/validator/validators/body.ts, packages/http/src/validator/validators/params.ts, packages/http/src/validator/validators/utils.ts
1. Correctly catch exception in the rare case the validation fails
2. Do not coerce the payload during the validation in case we're treating JSON stuff since the JSON parser of V8 will keep the types
3. Do not create JSON Schemas in case there are no properties in the params
4. Add tests
Closes #894
=> fix: do not coerce types

CHANGELOG.md, packages/http/src/mocker/negotiator/InternalHelpers.ts, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts, packages/http/src/validator/utils/spec.ts, packages/http/src/validator/validators/__tests__/body.spec.ts, packages/http/src/validator/validators/body.ts
This PR will replace different checks we were doing in places to look for content so that instead of using regular string comparison we use the type-is library which will normalise content types with charset and so on
Closes #943
=> Use type-is for content type comparison

.github/workflows/markdown-links.yml, CHANGELOG.md, packages/http/src/client.ts
* Changes the markdown link checker that was just broken and reporting errors anytime
* Changes the way the internal logger is constructed so it does not crash anymore — this is required for Request Maker. Will trigger a release when this gets merged.
This is not idea, in the future I will make sure the logger is passed by the caller of the client, but this at least fixes the situation introduces with abstract-logger 2.x
=> fix: http client logger creation

packages/http-server/src/server.ts
Feature
When using axios and this prism mock server(with --cors and -d options), this prism mock server can't add response various headers.
this prism mock server can add various headers.
No
=> Add Access-Control-Expose-Headers for prism mock server

.circleci/config.yml, CHANGELOG.md, docs/guides/http-client.md, lerna.json, packages/cli/package.json, packages/cli/src/util/createServer.ts, packages/cli/src/util/runner.ts, packages/core/package.json, packages/core/src/types.ts, packages/http-server/package.json, packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http-server/src/server.ts, packages/http-server/src/types.ts, packages/http/package.json, packages/http/src/client.ts, packages/http/src/types.ts
* Adds documentation on partial urls
* Types the `CreatePrism` instances for a faster find next time I'll need to refactor them
* Moves the `errors` option (it was listed twice!) from the wrong place
* Small changes in the internal logging creation
* Removes `Error.captureStackTrace(this, ProblemJsonError);` — that function is V8 specific and does not work in other browsers
=> Client fixes

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/core/package.json, packages/core/src/types.ts, packages/http-server/package.json, packages/http/package.json, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/types.ts
I figured that we have defined the error class twice, for no reason. This PR removes the duplicate.
=> refactor: remove double error definition

CHANGELOG.md, packages/http/src/router/__tests__/index.spec.ts, packages/http/src/router/index.ts, test-harness/specs/routing/prefer-concrete-path.oas3.txt
Closes #981 
ServerMatch is `undefined`, not null.
=> Fix: check server presence correctly in disambiguiation

CHANGELOG.md, packages/http/src/client.ts
Prism's http-client is no longer returning `{}` when the body is empty.
=> fix: returning actual body

.dockerignore, Dockerfile
This pull request will modify the docker ignore file to remove some of the stuff we do not need to build the docker image for Prism, moving the context from 16Mb to 1Mb.
This is a byproduct of a more important bug that I fixed here — yarn, when used in workspace mode, will always try to hoist everything in the main `node_modules` directory — which is great.
The problem is that Dockerfile's copy for the children `node_modules`, in such case, might fail (because the hoisting has changed the game).
This PR makes sure that in the dev image a `node_modules` directory is always present — so that the copy will never fail.
On a different topic, I think the requirements for our docker images have changed a bit and most likely we can find a better way to organize this. Not now though.
=> fix: docker image restore

packages/http/src/__tests__/http-prism-instance.spec.ts, packages/http/src/utils/__tests__/parseResponse.spec.ts
Return from `assertResolvesLeft` instead of using async await
=> refactor: no await for assertResolvesLeft

CHANGELOG.md, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http-server/src/server.ts
Closes #1033 
`Object.assign` will assign and change properties even if they're undefined, merge does not.
```ts
Object.assign({dynamic: true},{dynamic: undefined})
// {dynamic: undefined}
merge({dynamic: true},{dynamic: undefined})
// {dynamic: true}
```
=> fix: use lodash merge for header options

CHANGELOG.md, docs/guides/errors.md, lerna.json, packages/cli/package.json, packages/core/package.json, packages/http-server/package.json, packages/http-server/src/server.ts, packages/http/package.json, packages/http/src/mocker/errors.ts, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts, test-harness/specs/default-responses/default_responses-AC-4.oas2.txt, test-harness/specs/default-responses/default_responses-AC-4.oas3.txt, test-harness/specs/default-responses/default_responses-AC-4.pc.txt
Create a specific error for Prism when it cannot find a suitable 2XX response so we can differentiate with something that's not under our control
=> feat: add custom error for 2**

lerna.json, package.json, packages/cli/package.json, packages/core/package.json, packages/http-server/package.json, packages/http/package.json, packages/http/src/mocker/negotiator/InternalHelpers.ts, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/validator/index.ts, packages/http/src/validator/utils/spec.ts, test-harness/specs/security/security-scheme-validation-AC-28.oas3.txt, yarn.lock
Needs the latest Http Spec package
Closes #1036
=> fix: upgrade http-spec

packages/http/src/forwarder/index.ts
Hi everyone,
This PR is to fix the issue #1075. 
The issue is in the `forwarder` because the request created override the `Accept` header by `application/json, text/plain, */*`.
That PR fix that issue preserving the header if it has been set and add to `application/json, text/plain, */*` if wasn't set.
Nicolas
=> Forward request to server without altering accept header

.github/CODEOWNERS, CHANGELOG.md, CONTRIBUTING.md, package.json, packages/http/package.json, packages/http/src/mocker/__tests__/functional.spec.ts, packages/http/src/mocker/negotiator/InternalHelpers.ts, packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/mocker/negotiator/__tests__/InternalHelpers.unit.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/index.ts, test-harness/specs/content-negotiation/E2E-Accept-Content-Negotiation-AC-16.oas3.txt, yarn.lock
This pull request implements a backup strategy to ignore parameters in content type when is possible. Since they're not standard (apart for the `q` value) we won't assume anything about it and drop them in some cases
Closes #1152
=> Compare content type parameters separately

.circleci/config.yml, CHANGELOG.md, package.json, packages/http/src/validator/validators/params.ts, test-harness/specs/validate-query-params/query-param-upper-case.oas2.txt
Closes #1267 
- Correctly lookup properties in lower case (this happens because query string and headers are case insensitive)
- Make the `createJsonSchema` function pure
- Auto publishes the master branch under the `beta` tag automagically
=> Correctly lookup the properties in lowercase

CHANGELOG.md
Publishing 3.3.6 with a bug fix back ported from 4 and pinning Lodahs to 4.17.15.
Closes #1282
=> Update changelog with 3.3.6

CHANGELOG.md, packages/http/src/forwarder/index.ts
Removing the compress flag will not only disable requesting compressed content but also disable the unzipping in case somebody is requesting it.
The correct solution Is to provide a default `accept-encoding` header so that `node-fetch` won't try to override it.
=> explicit accept encoding

CHANGELOG.md, packages/http/src/router/__tests__/matchPath.spec.ts, packages/http/src/router/matchPath.ts
Remove path start error, since there is nothing we can do from the Prism side and it's only harming our Sentry logs.
=> Remove path start error

CHANGELOG.md
Add changelog from 3.3.7 — the fix about the compressed resource was really needed in the wild.
=> Upgrade with 3.3.7 changelog

docs/guides/http-client.md
Let the user know that they can use the `mock` flag
=> Docs: document mock options

packages/cli/package.json, packages/cli/src/combinators.ts, packages/cli/src/util/paths.ts, packages/core/src/factory.ts, packages/http/package.json, packages/http/src/combinators.ts, packages/http/src/forwarder/index.ts, packages/http/src/mocker/callback/callbacks.ts, packages/http/src/mocker/index.ts, packages/http/src/utils/runtimeExpression.ts, packages/http/src/validator/index.ts, packages/http/src/validator/validators/utils.ts, yarn.lock
fp-ts 2.4 has built-in support for `bind` notation — allowing us to remove `fp-ts-contrib` and refactor some code.
=> Remove fp-ts-contrib

package.json, packages/http/src/mocker/generator/JSONSchema.ts, packages/http/src/mocker/generator/__tests__/HttpParamGenerator.spec.ts, packages/http/src/validator/deserializers/__tests__/registry.spec.ts, packages/http/src/validator/deserializers/style/__tests__/delimited.spec.ts, packages/http/src/validator/deserializers/style/__tests__/form.spec.ts, packages/http/src/validator/deserializers/style/__tests__/simple.spec.ts, yarn.lock
* Add types for json schema types
* Remove tests for what TypeScript can ensure us
--- 
Next: remove the `supports` method and make it a static map.
=> Fix: types

docs/getting-started/01-installation.md
From the Docker documentation https://docs.docker.com/engine/reference/commandline/run/
> - P : Publish all exposed ports to random port
much better to specify the port to expose using `-p` as in the last example.
=> Standardized Docker commands

CHANGELOG.md, packages/http/src/validator/__tests__/__snapshots__/functional.spec.ts.snap, packages/http/src/validator/validators/__tests__/utils.spec.ts, packages/http/src/validator/validators/utils.ts
When analyzing a payload being an array of something, and that one of the entries doesn't match the schema, the position isn't returned as part of the path. 
When the array is quite big, this makes it quite difficult to figure out which entry is malformed.
Given the second array element is wrong:
- `{ data: [{ id: 11 }, { nope: false }] }` => path currently returned: `data[1]`
- `[{ id: 11 }, { nope: false }]` => path currently returned: `(nothing)` (This PR attempts at making this better and returning `[1]`)
=> Teach convertAjvErrors to honor root array based paths

packages/http-server/package.json, packages/http-server/src/getHttpConfigFromRequest.ts, yarn.lock
Use the new io-ts decoding system and remove the types, since we can use the `parse` method.
=> Use new Decoders

packages/http-server/src/__tests__/getHttpConfigFromRequest.spec.ts, packages/http-server/src/getHttpConfigFromRequest.ts, packages/http-server/src/server.ts, packages/http/src/types.ts
This PR reduces the arguments the HTTP Request parameter extraction requires to do its job as well as renaming the function in ProblemJson to be more communicative.
This is feedback I gathered while doing some upgrades of Prism in Stoplight's platform.
P.S: This PR has been created exclusively from an iPad Air 4 using GitHub CodeSpaces and their native iOS app. :trollface:
=> Reduce function requirements and ProblemJson function name

packages/http/src/validator/validators/body.ts
There is no reason to map, we can reconstruct the context in the required function directly.
=> Remove Map Statement

packages/http/src/validator/validators/__tests__/body.spec.ts, packages/http/src/validator/validators/utils.ts
I've been receiving validation errors when using nullable: true in my OpenAPI schema.
This extends @nulltoken 's work here #1734 -- with the option described here.
Manually testing this locally appears to work as previously failing validations now pass 🥳 -- This unblocks us from using Prism in our E2E test suite.
=> Fix: Support nullable validations

packages/http/package.json, yarn.lock
Here's the list of changes introduced between the two releases
https://github.com/stoplightio/json-schema-sampler/compare/bdd5ae5a6e57289ef2508f8abb3065231d2d88a1~1...e096188662e08bd16e9f4982e69cd27f36b1df25
The meaningful change for Prism is basic support of `if` compound keyword.
https://github.com/stoplightio/json-schema-sampler/commit/e096188662e08bd16e9f4982e69cd27f36b1df25 is relatively important for platform, as otherwise we're forced to set a resolution.
It's not an issue with the code itself, but rather with the old version of Webpack we use in platform-internal.
I'm planning to trigger a minor release after this PR is merged.
=> chore(deps): bump @stoplight/json-schema-sampler from 0.1.0 to 0.2.0

packages/cli/src/util/__tests__/paths.spec.ts, packages/cli/src/util/paths.ts
Addresses [#1743]
Use encodeURI param names to avoid performance issues on startup.
See more details in the  https://github.com/stoplightio/prism/issues/1743#issuecomment-830021600 thread
=> Use encodeURI param names to avoid performance issues on start up.

.circleci/config.yml
To avoid python2/python3 issues
Error: Could not symlink Frameworks/Python.framework/Headers
Target /usr/local/Frameworks/Python.framework/Headers
is a symlink belonging to python@3.9. You can unlink it:
brew unlink python@3.9
Context
[Succeed build ](https://app.circleci.com/pipelines/github/stoplightio/prism/8146/workflows/63cee241-c0de-4a36-a61b-66afc1697baf)
[Failed Build](https://app.circleci.com/pipelines/github/stoplightio/prism/8143/workflows/91e94c6a-1d61-4ef4-a1cb-9a8a02613746/jobs/17049)
=> install pipenv with pip3

.github/pull_request_template.md, CONTRIBUTING.md, package.json, packages/cli/package.json, packages/cli/src/operations.ts, packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http-server/src/__tests__/fixtures/petstore.no-auth.circular.oas2.yaml, packages/http-server/src/__tests__/fixtures/petstore.no-auth.circular.oas3.yaml, packages/http-server/src/__tests__/server.oas.spec.ts, packages/http/package.json, packages/http/src/mocker/generator/HttpParamGenerator.ts, packages/http/src/mocker/generator/JSONSchema.ts, packages/http/src/mocker/generator/__tests__/JSONSchema.spec.ts, packages/http/src/mocker/index.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/index.ts, packages/http/src/validator/validators/body.ts, packages/http/src/validator/validators/headers.ts, packages/http/src/validator/validators/params.ts, packages/http/src/validator/validators/path.ts, packages/http/src/validator/validators/query.ts, packages/http/src/validator/validators/types.ts, packages/http/src/validator/validators/utils.ts, test-harness/specs/validate-body-params/form-byte-format-fail.oas2.txt, yarn.lock
Addresses https://github.com/stoplightio/prism/issues/1456
Blocked By https://github.com/stoplightio/json/pull/90
**Summary**
- switch to our forked json schema ref parser
- bundle http operations
- validate circular data properly
- dynamically generate data for circular structures
- tests
**Checklist**
- The basics
- Tests
=> feat: support circular refs

packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http-server/src/server.ts
Addresses #1814
**Summary**
Configure `micri` to accept requests of up to 10MB instead of just 1MB so that users can send larger requests without any additional effort.
Why 10MB? Because [_10MB ought to be enough for anybody_](https://en.wikiquote.org/wiki/Talk:Bill_Gates). ;p
**Checklist**
- The basics
- Tests
In order to mock a service that accepts images in the request body, I need to increase the maximum request size limit.
10MB is enough for my use case and was suggested by @philsturgeon, this could be a configuration option in the future if different use cases come up.
=> Increase max request size to 10mb by default

packages/http/src/mocker/generator/JSONSchema.ts, packages/http/src/mocker/generator/__tests__/JSONSchema.spec.ts, packages/http/src/utils/__tests__/filterRequiredProperties.test.ts, packages/http/src/utils/filterRequiredProperties.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/index.ts, packages/http/src/validator/validators/__tests__/body.spec.ts, packages/http/src/validator/validators/body.ts, packages/http/src/validator/validators/types.ts
`validate` requires a new context parameter, that will define validation context - input or output. Based on the context either readOnly or writeOnly parameters will be removed from the required list.
Addresses #1142
**Summary**
**Checklist**
- The basics
- Tests
> Read-Only and Write-Only Properties
> If a readOnly or writeOnly property is included in the required list, required affects just the relevant scope – responses only or requests only. That is, read-only required properties apply to responses only, and write-only required properties – to requests only.
This PR based on @marcelltoth PR …
=> readOnly and writeOnly support v2

packages/http/src/validator/__tests__/__snapshots__/functional.spec.ts.snap, packages/http/src/validator/__tests__/functional.spec.ts, packages/http/src/validator/validators/dateTime.ts, packages/http/src/validator/validators/utils.ts
Addresses #1830 
**Summary**
Replaces the date-time validator provided by ajv-formats with the original functionality + our bug fix from https://github.com/ajv-validator/ajv-formats/pull/33.
Based on the conversation on https://github.com/ajv-validator/ajv-formats/pull/33 this bug fix won't be accepted into ajv-formats for awhile, if at all.
**Checklist**
- The basics
- Tests
=> fix: replace date-time validator with our bug fixed version

docs/guides/06-errors.md
**Summary**
There is invalid white space in `06-erros.md`. so `###` is not parsed as header.
**Checklist**
- The basics
- Tests
=> minor doc fix

packages/http-server/README.md
In #1009 the getHttpOperationsFromSpec moved to the prism-cli package. The documentation needs to be updated accordingly
=> Update Http-server doc with new location of getHttpOperationsFromSpec

packages/cli/package.json, packages/cli/src/operations.ts, yarn.lock
Addresses #1860 
**Summary**
Uses fixes version of `@stoplight/json` that allows to preventing deep clone of document too many times since cloning was not necessary.
**Checklist**
- The basics
- Tests
=> fix: fixed #1860 performance regression

packages/http/src/router/__tests__/index.spec.ts, packages/http/src/router/__tests__/matchPath.spec.ts, packages/http/src/router/__tests__/utils.ts, packages/http/src/router/matchPath.ts, test-harness/specs/routing/support-encoded-path.oas3.txt
**Summary**
You have a spec with `/some path` in it and you're trying to mock this path with mocker. If you'll send an encoded path (`/some%20path`) to the mocker it wont be able to find a corresponding path in the spec at will throw `NO_PATH_MATCHED_ERROR` which is not correct.
**Checklist**
- The basics
- Tests
=> fix: decode path before matching it

packages/http/src/router/__tests__/matchPath.spec.ts, packages/http/src/router/matchPath.ts
**Summary**
Some quick fixes to `matchPath` and related tests:
- Drop code related to special casing the column character (`:`). It's no longer needed.
- Incidentally this fixes a bug where `/part/ab:17/process` wasn't considered a valid match for `/part/{something}/process`
- Fix a code regression that was show casing as a flaky test
- Created a specific test case to isolate (and fix) the regression. The issue wasn't caught by CI builds, because most of the dynamically generated test cases were statistically comparing against **partially** templated paths (eg `/a/b/c` vs `/{d}/e/{f}/g`).
- Added a guard to ensure processed paths always start with a leading slash
- Fixed a related test that was passing for the wrong reason
**Checklist**
- The basics
- Tests
- Error …
=> Minor matchPath fixes

packages/http/src/validator/validators/__tests__/utils.spec.ts, packages/http/src/validator/validators/utils.ts
**Summary**
In ajv-validator/ajv#466, the author of AJV makes it very clear that people should be aware of unknown formats.
However, according to the OpenAPI spec, format is is an open string-valued property, and can have any value.
Given some traffic, all those warnings tend to pollute the console output a lot and make it very hard to follow up with what's logged by Prism.
This change intercepts AJV calls to console.warn and when they relate to unknown formats, silence them.
**Checklist**
- The basics
- Tests
Given the following spec `openapi.yaml` stored at the root of the repo workdir
```yaml
openapi: 3.1.0
paths:
/something:
get:
summary: Gimme me something, anything!
responses:
"200":
description: OK
content:
application/json: …
```
=> Teach Prism to stop polluting the console with AJV "unknown format" warnings

package.json, packages/http/src/__tests__/memory-leak-prevention.spec.ts, packages/http/src/__tests__/test-helpers.ts, packages/http/src/client.ts, packages/http/src/validator/validators/body.ts, packages/http/src/validator/validators/params.ts, packages/http/src/validator/validators/utils.ts, packages/tsconfig.test.json
Addresses #1881
**Summary**
**Checklist**
- The basics
- Tests
We've been recreating schema for params everytime, therefore any we couldn't effectively cache validation function created by ajv.
=> fix: #1881 fixed memory leak for validation

packages/http/src/forwarder/index.ts, packages/http/src/forwarder/resources.ts
Addresses #1064
**Summary**
In proxy mode, when a client requests an endpoint with "Accept-Encoding: gzip" we fetched compressed response but node-fetch decompress content automatically so we can validate response format. We send back a decompressed response but at the same time we pass back original headers that contain "Content-Encoding: gzip". In the end the client gets `Content-Encoding: gzip` header and tries to decompress the content and gets an error since the content is already decompressed.
**Checklist**
- The basics
- Tests
**Steps to reproduce**
[prism_testing.zip](https://github.com/stoplightio/prism/files/7569403/prism_testing.zip)
- import Postman collection from the attached files
- run Prism in proxy mode `yarn cli  proxy …
=> Removes `content-encoding` response header since we decompressed response body

packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http/package.json, packages/http/src/validator/validators/__tests__/body.spec.ts, packages/http/src/validator/validators/body.ts, yarn.lock
Addresses #1920 
When validating input, `readOnly` properties inside `allOf` should be omitted from normalized schema.  That is, it should never be required to supply a `readOnly` property in input.  Prior to this change, if the `readOnly` attribute was used within an `allOf`, it was not correctly removed from the "normalized" schema against which we'll validate. 
- The basics
- Tests
Some open questions exist; see comments inline in changes/diffs.
=> for input validation, readOnly properties inside allOf are omitted from normalized schema

docs/guides/06-errors.md
Getting this error in latest prism (v4.6.1) surprised me, as it was no error back in v4.4.1
And minor MD formatting fix.
=> INVALID_CONTENT_TYPE error for empty content

docs/getting-started/03-cli.md, packages/cli/src/commands/__tests__/commands.spec.ts, packages/cli/src/commands/proxy.ts, packages/cli/src/util/createServer.ts
Addresses #1694 
**Summary**
This pull request adds a `--validate-request` flag to the proxy CLI. The default value is `true` (as it was before). Passing `false` means that incoming HTTP requests will not be validated.
**Checklist**
- The basics
- Tests
=> feat(proxy): add a flag to skip request validation

packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http/src/validator/index.ts, test-harness/specs/validate-body-params/enforce-content-type-if-body-included.oas3_1.txt, test-harness/specs/validate-body-params/ignore-content-type-if-empty-body.oas3_1.txt
Addresses #1939
**Summary**
inspects the request content-length header for making the decision to enforce the content-type on the request. if it is >1 then the content-type header must be one of the request body types.
**Checklist**
- The basics
- Tests
=> allow for empty request bodies to skip validation, fixes #1939

packages/http/src/__tests__/client.spec.ts, packages/http/src/client.ts, packages/http/src/forwarder/__tests__/index.spec.ts, packages/http/src/forwarder/index.ts, packages/http/src/mocker/index.ts
**Summary**
Replace depreacted parse function to WHATWG URL.
**Checklist**
- The basics
- Tests
=> fix: remove deprecated usage of parse

docs/guides/01-mocking.md, packages/http/src/mocker/generator/__tests__/JSONSchema.spec.ts
Addresses https://github.com/stoplightio/prism/issues/1647#issuecomment-1064174921
Faker can be configured per-property, but there were no examples of this either in tests or documentation.
- The basics
- Tests
```yaml
openapi: 3.0.0
info:
title: issue
version: '1.0'
description: asdf
contact:
email: example@example.com
tags: []
servers: []
paths:
/200:
parameters: []
get:
description: asdf
tags: []
summary: example
operationId: example
responses:
'200':
description: OK
content:
application/json:
schema:
type: object
properties:
ten-or-eleven:
type: number
example: 10
x-faker:
datatype.number:
min: 10
max: 11
slug:
type: string
example: two-words
x-faker:
helpers.slugify:
- "two words"
components:
schemas: {}
securitySchemes: {}
```
Running `prism-cli …
=> document, test per-property faker configuration

docs/getting-started/03-cli.md
Removed: Query string parameters are deprecated and will be removed in the next major release.
=> Removed deprecated wording

.circleci/config.yml, Dockerfile, README.md, packages/cli/package.json, packages/core/package.json, packages/http-server/package.json, packages/http/package.json
Addresses #2022 
**Summary**
This PR upgrades the minimum node engine version from 12 to 16, as node version 12 is [approaching end-of-life](https://nodejs.org/en/about/releases/) on 04-30-2022. Specifying the minimum version of 16 will allow us to use dependencies that require a minimum version of 16. 
**Checklist**
- The basics
- Tests
N/A
=> Upgrading minimum node engine to 16

.circleci/config.yml
Upgrade the xcode image so that it brings in node 16 to be compatible with our node 16 upgrade.
https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
=> upgrade the macOs xcode image to get node 16

packages/http/src/forwarder/__tests__/index.spec.ts, packages/http/src/forwarder/index.ts, packages/http/src/utils/url.ts
Addresses a regression in 4.9.0
**Summary**
Prism 4.9.0 was not passing query string values when forwarding a request. The `format` change, didn't account for a change from `query` into `search`
**Checklist**
- The basics
- Tests
=> ensure the forwarder passes query or search string values

packages/http/src/mocker/generator/JSONSchema.ts, packages/http/src/mocker/generator/__tests__/JSONSchema.spec.ts, test-harness/README.md, test-harness/helpers.ts, test-harness/index.ts, test-harness/specs/dynamic-responses/dynamic_json_alphabetize_response.oas2.txt
Ordering by the original JSON schema would be optimal but this seems better than random?
Addresses #2038 
**Summary**
Json parameters are returned in (random?) order from dynamic mocking.  Ugly at best, hard to find what you are looking for.
**Checklist**
- The basics
- Tests
Please overly scrutinize this, but also be gentle ;) -  I'd love to be helpful but don't want my help to be detrimental.  And I'm pretty new to TypeScript generally.
Obvious concerns are recursion, typing, unintended consequences - I don't know the project context.
It also seems like https://github.com/json-schema-faker/json-schema-faker might be the place to really address some of this?
=> Added alphabetical ordering to generated objects 

README.md, packages/cli/src/util/__tests__/paths.spec.ts, packages/http-server/src/__tests__/body-params-validation.spec.ts, packages/http/package.json, packages/http/src/__tests__/fixtures/index.ts, packages/http/src/mocker/callback/__tests__/callbacks.spec.ts, packages/http/src/mocker/generator/JSONSchema.ts, packages/http/src/mocker/generator/__tests__/HttpParamGenerator.spec.ts, packages/http/src/mocker/generator/__tests__/JSONSchema.spec.ts, packages/http/src/mocker/negotiator/__tests__/InternalHelpers.unit.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts, packages/http/src/router/__tests__/index.spec.ts, packages/http/src/router/__tests__/matchBaseUrl.spec.ts, packages/http/src/router/__tests__/matchPath.spec.ts, packages/http/src/router/__tests__/utils.ts, packages/http/src/validator/__tests__/functional.spec.ts, packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/utils/__tests__/spec.spec.ts, packages/http/src/validator/validators/__tests__/body.spec.ts, packages/http/src/validator/validators/__tests__/headers.spec.ts, packages/http/src/validator/validators/__tests__/path.spec.ts, packages/http/src/validator/validators/__tests__/query.spec.ts, packages/http/src/validator/validators/security/__tests__/security.spec.ts, yarn.lock
Addresses #1968
**Summary**
This PR replaces the compromised [faker](https://www.npmjs.com/package/faker) dependency with the official community-maintained [@faker-js/faker](https://www.npmjs.com/package/@faker-js/faker) dependency. The contents of the dependency (and version number) are the same. 
**Checklist**
- The basics
- Tests
N/A
=> Update faker dependency to point to official community-maintained version

packages/http/src/validator/__tests__/index.spec.ts, packages/http/src/validator/utils/__tests__/wildcardMediaTypeMatch.spec.ts, packages/http/src/validator/utils/wildcardMediaTypeMatch.ts
**Summary**
Adds support for wildcard mimetypes in response definitions. This is supported by the spec: https://spec.openapis.org/oas/v3.1.0#path-item-object-example
**Checklist**
- The basics
- Tests
=> Support for wildcard mimetypes in mock response

packages/cli/src/util/__tests__/paths.spec.ts, packages/cli/src/util/paths.ts, packages/http/src/mocker/serializer/style/__tests__/deepObject.spec.ts, packages/http/src/mocker/serializer/style/deepObject.ts
Addresses #2058 
**Summary**
Allow nullable properties inside a [`deepObject` styled](https://swagger.io/docs/specification/serialization/#query) object.
**Checklist**
- The basics
- Tests
=> allow nullable properties in deepobject style

yarn.lock
Addresses #2010
**Summary**
Updates 2 dependencies to get rid of the last 2 moderate security vulnerabilities.
**Checklist**
- The basics
- Tests
=> fix: upgrade deps to clean up last security vulnerabilities

.github/workflows/auto-merge-dependabot.yml
**Summary**
Github action to enable auto merge for dependabot PRs.
Implemented according to GitHub's docs:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
=> add github action for enabling auto merge on dependabot PRs

.github/workflows/auto-approve.yml
**Summary**
The auto approve dependabot PRs action was [failing](https://github.com/stoplightio/prism/runs/7958887253?check_suite_focus=true).
This PR changes that action from using a marketplace thing, to conforming with the [GitHub docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request).
=> switch market place app with yaml described in github docs

.eslintignore, package.json, packages/cli/src/util/createServer.ts, packages/http/src/__tests__/memory-leak-prevention.spec.ts, test-harness/specs/multi-process-mode/smoke-test.oas3.text, yarn.lock
Addresses #2138
**Summary**
This fixes the mock command regression introduced in 4.10.4 by reverting [this commit ](https://github.com/stoplightio/prism/pull/2119/commits/f6c4e9f6929f65f40a7c8d1f35dc0c3ca691b80c).  The reason these breaking code changes were made was partly due to an issue with the type definitions for the core node cluster module.  See [this issue](https://github.com/stoplightio/prism/pull/2119/commits/f6c4e9f6929f65f40a7c8d1f35dc0c3ca691b80c).  I've added an .eslintignore as well because the lint errors were distracting when scanning the build output.
**Checklist**
- The basics
- Tests
Node 16.17 is in LTS as of today, and I'm not sure we should bump to 18 yet.  @types/node generally should line up with the …
=> 2138: Fix mock command regression

packages/cli/src/operations.ts
Addresses #2092. Happy Hacktoberfest!
**Summary**
Introduces a User-Agent request header when resolving remote OAS specs or Postman collections by passing the appropriate options to [json-schema-ref-parser](https://github.com/stoplightio/json-schema-ref-parser).
**Checklist**
- The basics
- Tests
Screenshot of a simple server that dumps headers:
=> Send a User-Agent when fetching remote spec content

yarn.lock
Addresses #2056 
**Summary**
Upgrading the lock file to match the latest `^6.0.0` version for `@faker-js/faker` to ensure the local build and NPM build are consistent. 
Upgrade was completed using the following command: 
```
yarn upgrade @faker-js/faker@^6.0.0
```
Then going through all of the other packages and running `yarn` to ensure locked values weren't improperly removed
**Checklist**
- The basics
- Tests
=> Upgrade the lock file for faker-js

docs/guides/01-mocking.md, docs/guides/11-dynamic-response-with-faker.md, toc.json
Related to #2056 and #2175. Closes https://github.com/stoplightio/platform-docs/issues/613.
**Summary**
Expand docs to explain Faker and JSON Schema Faker behavior.
=> docs(repo): update dynamic response generation with Faker details

packages/cli/src/commands/__tests__/commands.spec.ts, packages/cli/src/util/createServer.ts, packages/core/src/logger.ts
Addresses bug introduced in PR #2231
**Summary**
There is a bug in my recently accepted pull request #2331 for verbose logging options. In PR #2331, I set custom log levels to the same log severity level as Pino's "info" level. However, when I did this all such levels ("info" and all custom levels) would end up all logging as whatever custom log name last overrode the severity rank value. For instance, if we had "info", "success", and "start" all set to 30, all logs at this level would show up as "start." I originally approached it this way so that we support an arbitrary number of custom log levels showing up when the debug level is "info", rather than limiting it to 9 (i.e. levels at 31-39 until we hit "warn" at 40). I did some digging and apparently this is a known bug in Pino: …
=> Remove conflicting log levels due to Pino bug

packages/http/src/utils/__tests__/parseResponse.spec.ts, packages/http/src/utils/parseResponse.ts
Addresses ----
**Summary**
Currently, the response is parsed as json when content-type of `application/json`.  However in the case of `204` responses, this should not happen as the body would be empty and will raise an exception.
**Checklist**
- The basics
- Tests
We recently ran into an issue where an endpoint returns a response with header `Content-type: application/json` on a `204 No Content` status code. This was raising an exception as the body was getting parsed as json. As it seems the behavior is to read body as text on all non `application/json` response types, I think it should be safe to do the same for 204 responses as well since a valid json body is not expected.
=> Don't parse response body as json on 204

packages/http-server/src/server.ts, packages/http/src/forwarder/errors.ts, packages/http/src/forwarder/index.ts, test-harness/specs/proxy/proxy.get-null-body.txt, test-harness/specs/proxy/proxy.get-with-body.txt
Addresses #2255
**Summary**
* removes `Content-Type` as a detection mechanism for request bodies
* adds more detailed error when the proxy detects a request body in a GET/HEAD request, which `node-fetch` does not support
**Checklist**
- The basics
- Tests
=> feat: adds more standard compliant request body handling

package.json, packages/http-server/package.json, packages/http-server/src/serialize.ts, test-harness/helpers.ts, yarn.lock
Addresses https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-3325616
**Summary**
Upgrades fast-xml-parser from 3.20.3 to 4.2.0 to address https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-3325616
**Checklist**
- The basics
- Tests
I haven't tested extensively, but the tests pass. The only breaking change upstream appeared to be the renaming of `j2xParser` and its `parse` method to `XMLBuilder` and `build` respectively.
=> Upgrade fast-xml-parser to 4.2.0

CHANGELOG.md, packages/http/package.json
when verbose logging was added, the `chalk` dependency was not added to the http package.json file. this should fix some problems with the package
=> fix(http): add explicit dependency on chalk

CHANGELOG.md, packages/cli/package.json, yarn.lock
Addresses #2270
**Summary**
http-basic auth via the url is blocked by `fetch` in node 18+. this upgrade of jsrp supports converting that to an auth header as appropriate.
**Checklist**
- The basics
- Tests
=> fix: upgrade jsrp to 9.2.4 to allow basic auth

.gitignore, CHANGELOG.md, packages/http-server/src/server.ts, test-harness/specs/proxy/proxy.validation.httpHeader-truncated.txt
Addresses #2129
**Summary**
limiting the `sl-violations` header to around 8k, with a warning up front that it was too long
**Checklist**
- The basics
- Tests
=> chore: limit sl-volations header to around 8kb

packages/cli/package.json, yarn.lock
#2195 
**Summary**
Upgrade dependency `@stoplight/json-schema-ref-parser` in order to get a better error message when a `$ref` cannot be resolved.
Rather than the error message
```
Token "definitions" does not exist.
```
instead provide the message
```
at "#/components/examples/AppUserSchemaResponse/value/properties/profile/allOf/0", token "definitions" in "#/definitions/base" does not exist
```
**Checklist**
- The basics
- Tests
=> 2195 upgrade @stoplight/json-schema-ref-parser

README.md
Addresses #2305 
**Summary**
Prism requires NodeJS 18.16 or later due to [an upstream bug in undici in NodeJS 18.15](https://github.com/nodejs/undici/pull/1910#issuecomment-1478377261) (and possibly earlier).
**Checklist**
- The basics
- Tests
N/A
N/A
=> 2305 document Node 18.16-or-later requirement

packages/cli/src/commands/mock.ts, packages/cli/src/commands/proxy.ts, packages/cli/src/extensions.ts, packages/cli/src/util/createServer.ts, test-harness/specs/json-schema-faker-fillProperties/fillProperties_false.txt, test-harness/specs/json-schema-faker-fillProperties/fillProperties_false_json_schema_faker_config.txt, test-harness/specs/json-schema-faker-fillProperties/fillProperties_false_json_schema_faker_config_fillProperties_true.txt
Addresses #2046 
**Summary**
In an effort to make it easier to set the json schema faker `fillProperties` to false, without having to modify individual schemas, a new cli parameter has been added for mocking. 
With this change you can now run  `prism mock -d --json-schema-faker-fillProperties=false api.oas3.yaml` to ensure additional properties that are not explicitly named in your spec aren't returned when mocking. Setting this value with the command line will take priority over the value set in `x-json-schema-faker`
**Additional Background**
When using dynamic mocking, if `additionalProperties` is not set on each `properties` in a schema, json schema faker will fill in additional properties due to Prism's current [global setting](https://github.com/stoplightio/prism/blob/8f03c80f3643d2e2 …
=> add json schema faker fill properties param

packages/http/src/validator/validators/__tests__/body.spec.ts, packages/http/src/validator/validators/body.ts
#2376 
**Summary**
Handles when uri decoding binary data fails.
**Checklist**
- The basics
- Tests
Using the following curl request:
```
curl -X POST -H "Content-Type: multipart/form-data" -F "profileImage=@/Users/chelsea/Downloads/1x1.png" "http://127.0.0.1:4010/anything"
```
the behavior is as follows for the different versions of Prism:
**Version 4.14.1**
**Version 5.3.1**
**Local With Fixes**
=> keep encoded value if decoding fails.

packages/http/src/validator/validators/security/__tests__/security.spec.ts, packages/http/src/validator/validators/security/handlers/index.ts, packages/http/src/validator/validators/security/handlers/none.ts, packages/http/src/validator/validators/security/index.ts
Addresses #2393
**Summary**
> Optional is supported, but we'd like to change that support. Currently, the support is such that if Optional is included as a valid scheme, you can hand prism any authorization header (malformed, from a security type that isn't supported explicitly, etc) - and this will return a 200.
>
> Given an endpoint that supports, say, Basic OR None, this should be interpreted as - either don't include an auth header (NONE case), or include one that is proper for the Basic.
I found it a bit tricky to cover every case, so I just covered the Authorization header case, which covers Basic, Bearer, OpenId, OAuth2.
**Checklist**
- The basics
- Tests
=> feat: better optional auth support

packages/http/src/validator/validators/security/__tests__/security.spec.ts, packages/http/src/validator/validators/security/handlers/index.ts, packages/http/src/validator/validators/security/handlers/none.ts, packages/http/src/validator/validators/security/index.ts
I messed up the PR merge for https://github.com/stoplightio/prism/pull/2395 because I'm so used to the defaults in `platform-internal`. Sorry about that. Take 2!
=> feat: better validation for optional auth

packages/http/src/validator/validators/__tests__/utils.spec.ts, packages/http/src/validator/validators/utils.ts
**Summary**
This PR appends the property name to the message of `unevaluatedProperties` error.
Before, it's difficult to find out which property is unevaluated if the object schema has a long list of properties.
```
{
"location": [
"response",
"body",
"context"
],
"severity": "Error",
"code": "unevaluatedProperties",
"message": "Response body property context must NOT have unevaluated properties"
},
```
After, the property name ('operation' in this example) is appended to the message.
```
{
"location": [
"response",
"body",
"context"
],
"severity": "Error",
"code": "unevaluatedProperties",
"message": "Response body property context must NOT have unevaluated properties: 'operation'"
},
```
**Checklist**
- The basics
- Tests
=> Show unevaluated property name in error msg

Dockerfile
Addresses #2514
**Summary**
Upgrades base image in Dockerfile to `node:18.20.1` to resolve vulnerabilities flagged on the docker image.
**Checklist**
- The basics
- Tests
N/A
N/A
=> chore: Update Dockerfile to node:18

Dockerfile
Follow up from #2515 
**Summary**
Appeases security tooling since the [updates to node](https://nodejs.org/en/blog/release/v18.20.3) causes some tools to moan.
**Checklist**
- The basics
- Ran the build locally, used it in my project and it seems to be working fine.
- Tests
- As far as I am aware, there's no tests for using the projects container in an end to end fashion?
- (I cannot find any documentation for this so I guess N/A?)
- [Z] N/A
=> chore: Update Dockerfile to node:18.20.3

docs/getting-started/03-cli.md
**Summary**
The 'Logging Options' paragraph had an extra ` in the log level list that was creating an empty inline code block that was throwing off the Markdown renderer.
I noticed this while checking the documentation website: https://docs.stoplight.io/docs/prism/beeaad4dc0227-prism-cli#logging-options
**Checklist**
- The basics
- Tests
Before:
After:
=> docs: fixed markdown formatting for 'Logging Options' paragraph

packages/http/src/mocker/negotiator/NegotiatorHelpers.ts, packages/http/src/mocker/negotiator/__tests__/NegotiatorHelpers.spec.ts
Addresses #2381
**Summary**
Added warn log message for mismatched exampleKey.
**Checklist**
- The basics
- Tests
=> fix(http-negotiator): #2381 add additional warn log message

.github/CODEOWNERS
updates code owners to the [Prism Owners](https://github.com/orgs/stoplightio/teams/prism-owners) team that is full of smartbear people.
=> chore: changing codeowners to team of smartbears

packages/cli/package.json, packages/http-server/package.json, packages/http/package.json, packages/http/src/router/__tests__/index.spec.ts, packages/http/src/router/index.ts, packages/http/src/router/matchPath.ts
Addresses STOP-448
**Summary**
We observe that the issue is occurring in mock server when OAS is having similar templated requests as below example. Request was getting mapped with wrong endpoint and mock server was returning 400 error code.
Consider following API endpoints defined in project spec. 
1.	[https://stoplight-local.com:8443/mocks/seeded-enterprise/mock/174/{initgPtyIdOrgId}/payments/{paymentId}](https://stoplight-local.com:8443/mocks/seeded-enterprise/mock/174/%7BinitgPtyIdOrgId%7D/payments/%7BpaymentId%7D)
2.	[https://stoplight-local.com:8443/mocks/seeded-enterprise/mock/174/{initgPtyIdOrgId}/payments/search](https://stoplight-local.com:8443/mocks/seeded-enterprise/mock/174/%7BinitgPtyIdOrgId%7D/payments/search)
we can find two paths here - 
1. …
=> fix: mock issue resolve for similar templated requests

packages/cli/package.json, packages/http/package.json, packages/http/src/mocker/index.ts, yarn.lock
Addresses #[STOP-184]
**Summary**
Reverting changes due breaking in prism
**Checklist**
- The basics
- Tests
[STOP-184]: https://smartbear.atlassian.net/browse/STOP-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: reverted changes and bump the JSON version

README.md
**Summary**
The roadmap links were no longer pointing to the related idea. They are now pointing to the correct submitted idea cards. I am not sure what causes these links to change, but the link will take you to the idea page if the specific idea card no longer exists so it will not result in a broken link. 
**Checklist**
- The basics
- Tests
=> chore(readme): update roadmap links

packages/cli/package.json
Addresses #[[2611](https://github.com/stoplightio/prism/issues/2611)]
**Summary**
`json-schema-faker@0.5.8` includes the patched version of `jsonpath-plus` against https://security.snyk.io/vuln/SNYK-JS-JSONPATHPLUS-7945884
**Checklist**
- The basics
- Tests
=> chore(deps-dev): bump json-schema-faker from 0.5.6 to 0.5.8

Dockerfile
**Summary**
Avoid a minor warning from Docker when building.
> While Dockerfile keywords can be either uppercase or lowercase, mixing case styles is not recommended for readability.
https://docs.docker.com/reference/build-checks/from-as-casing/
**Checklist**
- The basics
- Tests
```
$ docker build .
...
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)                                               0.1s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 11)                                              0.1s
...
$ docker version
Client: Docker Engine - Community
Version:           27.2.1
...
Server: Docker Engine - Community
Engine:
Version:          27.2.1
...
```
=> refactor(docker): AS casing match FROM

Dockerfile
**Summary**
Use [tini](https://github.com/krallin/tini) to handle kernel signals for Node.js, per https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
For example, this aids shutting down. In a Docker compose setup Docker will send SIGINT and wait ten seconds for the container to stop. Without tini, prism does not get the signal and the 10s timeout forces stopping. With tini, prism closes in under a second.
**Checklist**
- The basics
- Tests
=> fix(Docker): use tini to handle kernel signals
